window.ETHNOGRAPHY_BOOKS = [
  {
    "id": "ethnography-01",
    "title": "《维塔》(Vita)",
    "year": 2005,
    "author": "João Biehl",
    "publisher": "Princeton University Press",
    "summary": "追踪巴西收容机构中被遗弃的精神病患者，以一名女性的生命为核心线索。\n\n结合长期田野、照片民族志与档案追溯。\n\n国家与家庭共谋将无用之人逐入遗弃区。",
    "location": "Porto Alegre",
    "countryOrRegion": "Brazil",
    "lat": -30.0346,
    "lon": -51.2177,
    "sourceField": "巴西 - 阿雷格里港",
    "locationEn": "Brazil·Porto Alegre"
  },
  {
    "id": "ethnography-02",
    "title": "《多重身体》(The Body Multiple)",
    "year": 2002,
    "author": "Annemarie Mol",
    "publisher": "Duke University Press",
    "summary": "同一疾病在荷兰医院不同实践场景中呈现为多种截然不同的现实。\n\n跟踪检查、手术室、门诊等日常医学实践。\n\n疾病不是被发现的，而是在不同实践中被多元地制造出来的。",
    "location": "Utrecht",
    "countryOrRegion": "Netherlands",
    "lat": 52.0907,
    "lon": 5.1214,
    "sourceField": "荷兰 - 乌得勒支",
    "locationEn": "Netherlands·Utrecht"
  },
  {
    "id": "ethnography-03",
    "title": "《暴露下的生命》(Life Exposed)",
    "year": 2002,
    "author": "Adriana Petryna",
    "publisher": "Princeton University Press",
    "summary": "切尔诺贝利核灾后，乌克兰人以受损的身体换取国家补偿与公民权利。\n\n基辅及灾区田野调查结合政策文件研究。\n\n受苦的身体成为政治谈判资本，催生后苏联时代的新型公民身份。",
    "location": "Kyiv / Chernobyl Region",
    "countryOrRegion": "Ukraine",
    "lat": 50.2,
    "lon": 30.3,
    "sourceField": "乌克兰 - 基辅/切尔诺贝利区域",
    "locationEn": "Ukraine·Kyiv / Chernobyl Region"
  },
  {
    "id": "ethnography-04",
    "title": "《即兴医疗》(Improvising Medicine)",
    "year": 2012,
    "author": "Julie Livingston",
    "publisher": "Duke University Press",
    "summary": "博茨瓦纳唯一癌症病房中的照护、生死处置与医护伦理。\n\n长期病房民族志与患者及医护人员访谈。\n\n资源匮乏催生医疗即兴，既揭示全球卫生不平等，也彰显照护者的伦理创造力。",
    "location": "Gaborone",
    "countryOrRegion": "Botswana",
    "lat": -24.6282,
    "lon": 25.9231,
    "sourceField": "博茨瓦纳 - 哈博罗内",
    "locationEn": "Botswana·Gaborone"
  },
  {
    "id": "ethnography-05",
    "title": "《治疗共和国》(The Republic of Therapy)",
    "year": 2010,
    "author": "Vinh-Kim Nguyen",
    "publisher": "Duke University Press",
    "summary": "西非艾滋病危机中，抗病毒药物的稀缺分配如何重塑患者的身份与主体性。\n\n布基纳法索与科特迪瓦多地田野调查。\n\n获得治疗的机会制造了新型生命政治身份，药物分配即政治分配。",
    "location": "Burkina Faso / Côte d'Ivoire",
    "countryOrRegion": "West Africa",
    "lat": 10.5,
    "lon": -4.5,
    "sourceField": "西非 - 布基纳法索/科特迪瓦",
    "locationEn": "West Africa·Burkina Faso / Côte d'Ivoire",
    "sites": [
      {
        "lat": 12.3714,
        "lon": -1.5197
      },
      {
        "lat": 5.36,
        "lon": -4.0083
      }
    ]
  },
  {
    "id": "ethnography-06",
    "title": "《牧灵诊所》(The Pastoral Clinic)",
    "year": 2010,
    "author": "Angela Garcia",
    "publisher": "University of California Press",
    "summary": "新墨西哥州西裔社区代际传承的海洛因成瘾与难以言说的悲恸。\n\n埃斯帕诺拉河谷长期田野调查与家庭访谈。\n\n成瘾根植于土地丧失与历史创伤，是悲恸的身体表达，而非个人道德缺陷。",
    "location": "New Mexico, Española Valley",
    "countryOrRegion": "USA",
    "lat": 36.0,
    "lon": -106.1,
    "sourceField": "美国 - 新墨西哥州 埃斯帕诺拉河谷",
    "locationEn": "USA·New Mexico, Española Valley"
  },
  {
    "id": "ethnography-07",
    "title": "《债中生活》(Life in Debt)",
    "year": 2012,
    "author": "Clara Han",
    "publisher": "University of California Press",
    "summary": "圣地亚哥贫困社区在新自由主义改革下的债务、照护与亲密关系。\n\n长期社区民族志，深入家庭日常。\n\n债务渗透底层的伦理互助，重塑亲属间的依存关系，使照护本身成为负重的实践。",
    "location": "Santiago",
    "countryOrRegion": "Chile",
    "lat": -33.4489,
    "lon": -70.6693,
    "sourceField": "智利 - 圣地亚哥",
    "locationEn": "Chile·Santiago"
  },
  {
    "id": "ethnography-08",
    "title": "《新鲜的水果，破碎的身体》(Fresh Fruit, Broken Bodies)",
    "year": 2013,
    "author": "Seth Holmes",
    "publisher": "University of California Press",
    "summary": "墨西哥移民农工在美国的迁徙、劳动与身体受苦。\n\n亲身随工人下地务农的参与式观察。\n\n结构性暴力与种族化将不平等铭刻于工人身体，并将他们的痛苦自然化、正常化。",
    "location": "Mexico (Oaxaca)",
    "countryOrRegion": "USA (Washington State)",
    "lat": 17.0732,
    "lon": -96.7266,
    "sourceField": "美国（华盛顿州）- 墨西哥（瓦哈卡）",
    "locationEn": "USA (Washington State)·Mexico (Oaxaca)",
    "sites": [
      {
        "lat": 48.4193,
        "lon": -122.3349
      },
      {
        "lat": 17.0732,
        "lon": -96.7266
      }
    ]
  },
  {
    "id": "ethnography-09",
    "title": "《权力的病理学》(Pathologies of Power)",
    "year": 2003,
    "author": "Paul Farmer",
    "publisher": "University of California Press",
    "summary": "全球贫富不平等如何系统性地剥夺海地、秘鲁等地人群的健康权利。\n\n多地临床田野调查与跨学科批判分析。\n\n结构性暴力是疾病的根源；健康即人权，医学人类学必须直面社会不正义。",
    "location": "Haiti, Peru, Russia, Cuba",
    "countryOrRegion": "Haiti, Peru, Russia, Cuba",
    "lat": 19.0,
    "lon": -72.3,
    "sourceField": "海地、秘鲁、俄罗斯、古巴",
    "locationEn": "Haiti, Peru, Russia, Cuba",
    "sites": [
      {
        "lat": 18.5944,
        "lon": -72.3074
      },
      {
        "lat": -12.0464,
        "lon": -77.0428
      },
      {
        "lat": 55.7558,
        "lon": 37.6173
      },
      {
        "lat": 23.1136,
        "lon": -82.3666
      }
    ]
  },
  {
    "id": "ethnography-10",
    "title": "《两度死亡》(Twice Dead)",
    "year": 2002,
    "author": "Margaret Lock",
    "publisher": "University of California Press",
    "summary": "脑死亡定义与器官移植在日本与北美引发的截然不同的认知与争议。\n\n跨文化比较民族志与医学史研究。\n\n死亡是社会建构而非生物事实；文化的局部知识塑造了不同的身体政治。",
    "location": "Tokyo / North America - Montréal etc.",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京 / 北美 - 蒙特利尔等",
    "locationEn": "Japan·Tokyo / North America·Montréal etc.",
    "sites": [
      {
        "lat": 35.6762,
        "lon": 139.6503
      },
      {
        "lat": 45.5019,
        "lon": -73.5674
      }
    ]
  },
  {
    "id": "ethnography-11",
    "title": "《末日松茸》(The Mushroom at the End of the World)",
    "year": 2015,
    "author": "Anna Tsing（罗安清）",
    "publisher": "Princeton University Press",
    "summary": "松茸商品链串联美国、日本、中国、芬兰的劳动、生态与多物种关系。\n\n多点田野调查，追踪松茸从森林到市场的全程。\n\n在资本主义废墟中，非正规合作与多物种共存仍可孕育生机，挑战线性进步叙事。",
    "location": "Japan - China - Finland",
    "countryOrRegion": "USA (Oregon)",
    "lat": 44.0582,
    "lon": -121.3153,
    "sourceField": "美国（俄勒冈）- 日本（京都） - 中国（云南）- 芬兰（拉普兰）",
    "locationEn": "USA (Oregon)·Japan·China·Finland",
    "sites": [
      {
        "lat": 44.0582,
        "lon": -121.3153
      },
      {
        "lat": 35.0116,
        "lon": 135.7681
      },
      {
        "lat": 26.05,
        "lon": 103.15
      },
      {
        "lat": 66.5039,
        "lon": 25.7294
      }
    ]
  },
  {
    "id": "ethnography-12",
    "title": "《森林如何思考》(How Forests Think)",
    "year": 2013,
    "author": "Eduardo Kohn",
    "publisher": "University of California Press",
    "summary": "厄瓜多尔卢纳人与亚马逊森林之间的符号互动与跨物种共处方式。\n\n阿维拉社区长期田野调查，结合皮尔斯符号学理论。\n\n符号与思考超越人类边界；森林本身是自我组织的符号过程，呼唤超越人类的人类学。",
    "location": "Avila",
    "countryOrRegion": "Ecuador",
    "lat": -0.67,
    "lon": -77.72,
    "sourceField": "厄瓜多尔 - 阿维拉",
    "locationEn": "Ecuador·Avila"
  },
  {
    "id": "ethnography-13",
    "title": "《在棕榈树的阴影下》(In the Shadow of the Palms)",
    "year": 2022,
    "author": "Sophie Chao",
    "publisher": "Duke University Press",
    "summary": "油棕种植园扩张对印尼西巴布亚马林德人多物种世界的系统性摧毁。\n\n社区民族志与多物种田野考察。\n\n工业农业造成存在性灾难：不仅是生态危机，更是本体论意义上的世界终结与哀悼。",
    "location": "West Papua, Maro River Region",
    "countryOrRegion": "Indonesia",
    "lat": -8.49,
    "lon": 140.39,
    "sourceField": "印尼 - 西巴布亚 莫劳河区域",
    "locationEn": "Indonesia·West Papua, Maro River Region"
  },
  {
    "id": "ethnography-14",
    "title": "《飞行之路》(Flight Ways)",
    "year": 2014,
    "author": "Thom van Dooren",
    "publisher": "Columbia University Press",
    "summary": "濒危鸟类的灭绝过程、保育劳动及其引发的伦理困境。\n\n跟随保育工作者与鸟类的多地民族志。\n\n灭绝是世代延续的生活方式之终结；哀悼与伦理责任是回应物种消失的恰当姿态。",
    "location": "Australia, USA (Hawaiʻi)",
    "countryOrRegion": "Australia, USA (Hawaiʻi)",
    "lat": 21.3069,
    "lon": -157.8583,
    "sourceField": "澳大利亚、美国（夏威夷）",
    "locationEn": "Australia, USA (Hawaiʻi)",
    "sites": [
      {
        "lat": 21.3069,
        "lon": -157.8583
      },
      {
        "lat": -33.8688,
        "lon": 151.2093
      }
    ]
  },
  {
    "id": "ethnography-15",
    "title": "《动物亲缘》(Animal Intimacies)",
    "year": 2018,
    "author": "R. Govindrajan",
    "publisher": "University of Chicago Press",
    "summary": "印度库曼山区人与动物间的情感、献祭与日常共处关系。\n\n社区参与观察与深度访谈。\n\n人与动物通过照料与暴力建立亲缘；跨物种关系挑战人类中心主义的亲密边界。",
    "location": "Kumaon Hills",
    "countryOrRegion": "India",
    "lat": 29.6,
    "lon": 79.6,
    "sourceField": "印度 - 库曼山区",
    "locationEn": "India·Kumaon Hills"
  },
  {
    "id": "ethnography-16",
    "title": "《猪肉城》(Porkopolis)",
    "year": 2020,
    "author": "Alex Blanchette",
    "publisher": "Duke University Press",
    "summary": "美国中西部工业猪肉生产中人与猪如何共同被纳入资本主义生产流水线。\n\n在屠宰场长期从业的深度参与民族志。\n\n工业单一文化将猪的生物节律强加于人类劳动，人与动物一同被化约为生产单元。",
    "location": "Midwest (Nebraska etc.)",
    "countryOrRegion": "USA",
    "lat": 41.5,
    "lon": -99.8,
    "sourceField": "美国 - 中西部（内布拉斯加州等）",
    "locationEn": "USA·Midwest (Nebraska etc.)"
  },
  {
    "id": "ethnography-17",
    "title": "《异星海洋》(Alien Ocean)",
    "year": 2009,
    "author": "Stefan Helmreich",
    "publisher": "University of California Press",
    "summary": "海洋微生物学家对深海生命边界的科学探索与认知建构。\n\n实验室与科考船田野调查。\n\n深海微生物挑战关于生命与自然的既有范畴；科学实践与资本共同建构海洋的本体。",
    "location": "Hawaiʻi / California Labs & Open Ocean",
    "countryOrRegion": "USA",
    "lat": 23.0,
    "lon": -155.0,
    "sourceField": "美国 - 夏威夷/加州实验室及公海",
    "locationEn": "USA·Hawaiʻi / California Labs & Open Ocean"
  },
  {
    "id": "ethnography-18",
    "title": "《去殖民化灭绝》(Decolonizing Extinction)",
    "year": 2018,
    "author": "J. S. Parreñas",
    "publisher": "Duke University Press",
    "summary": "马来西亚砂拉越猩猩康复机构中的照护实践、与殖民遗产的纠缠。\n\n机构民族志与工作者深度访谈。\n\n保育工作内嵌于殖民关系；去殖民化需正视照护行为的矛盾性，而非浪漫化救援。",
    "location": "Sarawak",
    "countryOrRegion": "Malaysia",
    "lat": 2.5,
    "lon": 113.5,
    "sourceField": "马来西亚 - 砂拉越",
    "locationEn": "Malaysia·Sarawak"
  },
  {
    "id": "ethnography-19",
    "title": "《与牧群共生》(Living with Herds)",
    "year": 2011,
    "author": "Natasha Fijn",
    "publisher": "Cambridge University Press",
    "summary": "蒙古游牧民与畜群之间的共同演化、日常互动与相互塑造。\n\n与牧民共同生活的长期参与田野调查。\n\n家畜是具有能动性的伙伴；人与动物通过长期共处形成跨物种的关系性社会。",
    "location": "Arkhangai Mountains",
    "countryOrRegion": "Mongolia",
    "lat": 47.7,
    "lon": 101.0,
    "sourceField": "蒙古 - 杭爱山脉",
    "locationEn": "Mongolia·Arkhangai Mountains"
  },
  {
    "id": "ethnography-20",
    "title": "《道德实验室》(Moral Laboratories)",
    "year": 2014,
    "author": "Cheryl Mattingly",
    "publisher": "University of California Press",
    "summary": "洛杉矶非裔美国家庭在照护慢性病儿童过程中的日常道德实践。\n\n长期家庭民族志与叙事分析。\n\n伦理是在实验与叙事中生成的实践，而非规则遵循；普通家庭是真实的道德哲学实验室。",
    "location": "Los Angeles",
    "countryOrRegion": "USA",
    "lat": 34.0522,
    "lon": -118.2437,
    "sourceField": "美国 - 洛杉矶",
    "locationEn": "USA·Los Angeles"
  },
  {
    "id": "ethnography-21",
    "title": "《成为罪人》(Becoming Sinners)",
    "year": 2004,
    "author": "Joel Robbins",
    "publisher": "University of California Press",
    "summary": "巴布亚新几内亚乌拉普明人皈依基督教后经历的道德与文化深层转型。\n\n部落社区长期田野调查。\n\n文化变迁可以是彻底的断裂；乌拉普明人真诚内化了基督教罪感伦理，而非表面融合。",
    "location": "Urapmin People",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.02,
    "lon": 141.57,
    "sourceField": "巴布亚新几内亚 - 乌拉普明部落",
    "locationEn": "Papua New Guinea·Urapmin People"
  },
  {
    "id": "ethnography-22",
    "title": "《正义的瘾君子》(Righteous Dopefiend)",
    "year": 2009,
    "author": "P. Bourgois",
    "publisher": "University of California Press",
    "summary": "旧金山无家可归海洛因成瘾者的日常生存、道德世界与相互照料。\n\n长期田野调查结合黑白照片民族志。\n\n成瘾者在结构性暴力中仍维系道德经济；社会排斥才是成瘾的根源，而非个体失德。",
    "location": "San Francisco",
    "countryOrRegion": "USA",
    "lat": 37.7749,
    "lon": -122.4194,
    "sourceField": "美国 - 旧金山",
    "locationEn": "USA·San Francisco"
  },
  {
    "id": "ethnography-23",
    "title": "《美德的主体》(The Subject of Virtue)",
    "year": 2013,
    "author": "James Laidlaw",
    "publisher": "Cambridge University Press",
    "summary": "印度耆那教苦行者的伦理修行实践与自由概念的人类学反思。\n\n斋浦尔苦行者社群的田野调查。\n\n美德需要自由；伦理不是习惯养成，而是自觉的自我培育，挑战功利主义与共同体主义。",
    "location": "Rajasthan / Jaipur",
    "countryOrRegion": "India",
    "lat": 26.9124,
    "lon": 75.7873,
    "sourceField": "印度 - 拉贾斯坦邦/斋浦尔",
    "locationEn": "India·Rajasthan / Jaipur"
  },
  {
    "id": "ethnography-24",
    "title": "《虔诚的政治》(Politics of Piety)",
    "year": 2005,
    "author": "Saba Mahmood",
    "publisher": "Princeton University Press",
    "summary": "开罗清真寺女性运动中的虔诚实践与伊斯兰伦理主体的形成。\n\n开罗女性清真寺运动的田野调查。\n\n服从与虔诚也是能动性的表达；质疑自由主义女性主义对能动性概念的狭隘预设。",
    "location": "Cairo",
    "countryOrRegion": "Egypt",
    "lat": 30.0444,
    "lon": 31.2357,
    "sourceField": "埃及 - 开罗",
    "locationEn": "Egypt·Cairo"
  },
  {
    "id": "ethnography-25",
    "title": "《生命之侧》(Life Beside Itself)",
    "year": 2014,
    "author": "Lisa Stevenson",
    "publisher": "University of California Press",
    "summary": "加拿大因纽特人的自杀危机与国家匿名照护机制的冷漠结构。\n\n努纳武特地区田野调查结合精神分析理论。\n\n国家照护管理生命却忽视灵魂；因纽特人的图像思维揭示另一种生命政治的可能。",
    "location": "Nunavut Territory",
    "countryOrRegion": "Canada",
    "lat": 66.0,
    "lon": -86.0,
    "sourceField": "加拿大 - 努纳武特地区",
    "locationEn": "Canada·Nunavut Territory"
  },
  {
    "id": "ethnography-26",
    "title": "《一心一意》(A Heart for the Work)",
    "year": 2010,
    "author": "Claire Wendland",
    "publisher": "University of Chicago Press",
    "summary": "马拉维医学生在资源极度匮乏条件下接受训练并形成医者伦理的过程。\n\n医学院与医院的田野调查。\n\n非洲医学培训塑造独特使命感；医生在匮乏中学会为工作奉献之心。",
    "location": "Blantyre",
    "countryOrRegion": "Malawi",
    "lat": -15.7861,
    "lon": 35.0058,
    "sourceField": "马拉维 - 布兰太尔",
    "locationEn": "Malawi·Blantyre"
  },
  {
    "id": "ethnography-27",
    "title": "《生存的意志》(The Will to Live)",
    "year": 2005,
    "author": "João Biehl",
    "publisher": "Princeton University Press",
    "summary": "巴西艾滋病患者如何通过法律诉讼争取免费药物，以及由此形成的生命政治格局。\n\n田野调查结合法律档案与患者访谈。\n\n生存的意志经由法律与制度化得以实现；巴西艾滋病治疗将药物可及性转化为公民权利。",
    "location": "Salvador",
    "countryOrRegion": "Brazil",
    "lat": -12.9777,
    "lon": -38.5016,
    "sourceField": "巴西 - 萨尔瓦多",
    "locationEn": "Brazil·Salvador"
  },
  {
    "id": "ethnography-28",
    "title": "《生活与言词》(Life and Words)",
    "year": 2006,
    "author": "Veena Das",
    "publisher": "University of California Press",
    "summary": "印度分治暴力与博帕尔灾难在德里贫民窟中留下的创伤记忆与日常承担。\n\n德里社区长期田野调查与深度对话式访谈。\n\n日常生活是消化暴力的场所；降入日常是幸存者在创伤裂缝中重建可居世界的生命实践。",
    "location": "Delhi",
    "countryOrRegion": "India",
    "lat": 28.6139,
    "lon": 77.209,
    "sourceField": "印度 - 德里",
    "locationEn": "India·Delhi"
  },
  {
    "id": "ethnography-30",
    "title": "《坠落的天空》(The Falling Sky)",
    "year": 2013,
    "author": "Davi Kopenawa",
    "publisher": "Harvard University Press",
    "summary": "亚诺马米萨满对本民族宇宙观、森林知识与生存危机的第一人称叙述。\n\n合作完成的自述式民族志，历时数十年。\n\n亚诺马米宇宙观构成对西方商品拜物教的深刻批判；萨满劳作维系着天空与世界。",
    "location": "Amazon Rainforest",
    "countryOrRegion": "Brazil / Venezuela",
    "lat": 1.0,
    "lon": -63.0,
    "sourceField": "巴西/委内瑞拉 - 亚马逊森林",
    "locationEn": "Brazil / Venezuela·Amazon Rainforest",
    "sites": [
      {
        "lat": 1.0,
        "lon": -63.0
      },
      {
        "lat": 3.5,
        "lon": -66.0
      }
    ]
  },
  {
    "id": "ethnography-31",
    "title": "《大地之灵》(Earth Beings)",
    "year": 2015,
    "author": "M. de la Cadena",
    "publisher": "Duke University Press",
    "summary": "秘鲁安第斯土著政治实践中非人类的大地存在（tirakuna）所扮演的能动角色。\n\n安第斯山区田野调查结合本体论分析。\n\n土著政治纳入了非人类存在；这颠覆了现代民主政治的人类中心主义前提。",
    "location": "Andes, Mt. Ausangate",
    "countryOrRegion": "Peru",
    "lat": -13.787,
    "lon": -71.229,
    "sourceField": "秘鲁 - 安第斯山区 奥桑加特山",
    "locationEn": "Peru·Andes, Mt. Ausangate"
  },
  {
    "id": "ethnography-32",
    "title": "《超越自然与文化》(Beyond Nature and Culture)",
    "year": 2013,
    "author": "Philippe Descola",
    "publisher": "University of Chicago Press",
    "summary": "对四种人类与非人类关系模式（泛灵论、图腾主义、类比论、自然主义）的跨文化比较。\n\n泛亚马逊田野调查结合结构分析。\n\n自然与文化的二元对立是西方独有的本体论；泛灵论等其他模式提供了同等有效的世界观。",
    "location": "Ecuador, Pan-Amazonian Region",
    "countryOrRegion": "Ecuador, Pan-Amazonian Region",
    "lat": -1.5,
    "lon": -76.5,
    "sourceField": "厄瓜多尔、泛亚马逊区域",
    "locationEn": "Ecuador, Pan-Amazonian Region"
  },
  {
    "id": "ethnography-33",
    "title": "《食人族形而上学》(Cannibal Metaphysics)",
    "year": 2014,
    "author": "E. V. de Castro",
    "publisher": "Univocal Publishing",
    "summary": "亚马逊原住民视角主义：所有存在共享文化视角，但拥有各自不同的身体与自然。\n\n比较神话学与跨部落民族志的理论重构。\n\n多自然主义颠覆西方多文化主义；原住民思想应被视为与西方哲学平等的智识传统。",
    "location": "Amazon Basin",
    "countryOrRegion": "Brazil",
    "lat": -3.0,
    "lon": -62.0,
    "sourceField": "巴西 - 亚马逊河流域",
    "locationEn": "Brazil·Amazon Basin"
  },
  {
    "id": "ethnography-34",
    "title": "《运动中的真理》(Truth in Motion)",
    "year": 2012,
    "author": "Martin Holbraad",
    "publisher": "University of Chicago Press",
    "summary": "古巴伊法占卜仪式中，神圣粉末与真理之间的本体论关系。\n\n哈瓦那伊法祭司社群的田野调查。\n\n粉末本身即真理而非象征真理；本体论转向要求我们从田野重建人类学分析概念。",
    "location": "Havana",
    "countryOrRegion": "Cuba",
    "lat": 23.1136,
    "lon": -82.3666,
    "sourceField": "古巴 - 哈瓦那",
    "locationEn": "Cuba·Havana"
  },
  {
    "id": "ethnography-35",
    "title": "《为多元宇宙设计》(Designs for the Pluriverse)",
    "year": 2018,
    "author": "Arturo Escobar",
    "publisher": "Duke University Press",
    "summary": "哥伦比亚土著与非裔社区对替代性自治生活方式与去殖民化设计的探索。\n\n参与式行动研究与社区田野调查。\n\n多元宇宙设计对抗全球化的单一世界逻辑；设计可以成为去殖民化的政治认识论实践。",
    "location": "Cauca Valley",
    "countryOrRegion": "Colombia",
    "lat": 2.5,
    "lon": -76.5,
    "sourceField": "哥伦比亚 - 考卡河谷",
    "locationEn": "Colombia·Cauca Valley"
  },
  {
    "id": "ethnography-36",
    "title": "《灵魂猎人》(Soul Hunters)",
    "year": 2007,
    "author": "Rane Willerslev",
    "publisher": "University of California Press",
    "summary": "西伯利亚尤卡吉尔猎人的模仿狩猎哲学：通过变成猎物来接近并诱捕它们。\n\n随猎人共同狩猎的深度参与民族志。\n\n猎人须在模仿与保持人性间维持危险平衡；泛灵论不是信仰，而是务实的存在论策略。",
    "location": "Siberia, Yukaghir Territory",
    "countryOrRegion": "Russia",
    "lat": 68.7,
    "lon": 153.0,
    "sourceField": "俄罗斯 - 西伯利亚 尤卡吉尔地区",
    "locationEn": "Russia·Siberia, Yukaghir Territory"
  },
  {
    "id": "ethnography-37",
    "title": "《现代性的神灵》(Spirits of Modernity)",
    "year": 2005,
    "author": "Harry G. West",
    "publisher": "University of Chicago Press",
    "summary": "莫桑比克穆埃达高原马孔德人的巫术话语与现代权力批判。\n\n高原社区田野调查结合政治历史分析。\n\n巫术是批判权力的本土语言；国家暴力与历史变迁通过巫术想象被体验、争议与诠释。",
    "location": "Mueda Plateau",
    "countryOrRegion": "Mozambique",
    "lat": -11.67,
    "lon": 39.56,
    "sourceField": "莫桑比克 - 穆埃达高原",
    "locationEn": "Mozambique·Mueda Plateau"
  },
  {
    "id": "ethnography-38",
    "title": "《美丽的生命政治》(The Biopolitics of Beauty)",
    "year": 2017,
    "author": "Alvaro Jarrín",
    "publisher": "University of California Press",
    "summary": "巴西公立医院中的整形手术如何将美丽建构为国家健康目标，揭示其与种族、阶级的历史纠缠。\n\n医院田野调查结合优生学历史档案与患者访谈。\n\n美被理论化为\"情感资本\"；整形手术制造了\"美学公民身份\"，在消解种族焦虑的表象下持续强化阶级与种族等级。",
    "location": "Rio de Janeiro / São Paulo",
    "countryOrRegion": "Brazil",
    "lat": -22.9068,
    "lon": -43.1729,
    "sourceField": "巴西 - 里约热内卢/圣保罗",
    "locationEn": "Brazil·Rio de Janeiro / São Paulo"
  },
  {
    "id": "ethnography-39",
    "title": "《私人生活的变革》(Private Life under Socialism)",
    "year": 2003,
    "author": "Yunxiang Yan（阎云翔）",
    "publisher": "Stanford University Press",
    "summary": "后社会主义时代农村礼物交换的衰退与个人情感生活的兴起，揭示私人领域的道德转型。\n\n长期田野调查与深度访谈，追踪1970至1990年代农村伦理变迁。\n\n国家退出与市场进入共同催生中国的个体化进程，个人权利意识在社会主义遗产的断裂处生长。",
    "location": "Heilongjiang, Xiajia Village",
    "countryOrRegion": "China",
    "lat": 46.0,
    "lon": 127.5,
    "sourceField": "中国 - 黑龙江下岬村",
    "locationEn": "China·Heilongjiang, Xiajia Village"
  },
  {
    "id": "ethnography-40",
    "title": "《中国女工》(Made in China)",
    "year": 2005,
    "author": "Pun Ngai（潘毅）",
    "publisher": "Duke University Press",
    "summary": "深圳电子厂流水线上的年轻农村女工如何在全球资本与国家之间被塑造为顺从的劳动主体。\n\n在工厂宿舍长期居住、并于车间与工人并肩工作的深度参与观察。\n\n身体的慢性疼痛既是规训的后果，也是无声的抵抗；性别与流动身份共同构成资本积累的结构性基础。",
    "location": "Guangdong, Shenzhen",
    "countryOrRegion": "China",
    "lat": 22.5431,
    "lon": 114.0579,
    "sourceField": "中国 - 广东深圳",
    "locationEn": "China·Guangdong, Shenzhen"
  },
  {
    "id": "ethnography-41",
    "title": "《城市中的陌生人》(Strangers in the City)",
    "year": 2002,
    "author": "Li Zhang（张鹂）",
    "publisher": "Stanford University Press",
    "summary": "中国城市化与市场化浪潮中，农村流动人口如何突破户籍制度限制，在北京形成大型移民社区并重组空间、权力与社会网络。\n\n以北京最大的流动人口社区为核心的详细民族志，追踪社区的建构、拆毁与重建过程。\n\n流动人口社区中的住房、市场空间和社会关系生产出非正式权力结构；后社会主义治理并非简单走向自由资本主义，而是在新的经济条件下重组国家与日常生活的关系。",
    "location": "Beijing, Zhejiangcun",
    "countryOrRegion": "China",
    "lat": 39.9042,
    "lon": 116.4074,
    "sourceField": "中国 - 北京浙江村",
    "locationEn": "China·Beijing, Zhejiangcun"
  },
  {
    "id": "ethnography-42",
    "title": "《跨越边界的社区》(Transcending Boundaries)",
    "year": 2005,
    "author": "Biao Xiang（项飙）",
    "publisher": "Brill",
    "summary": "北京\"浙江村\"的温州移民如何自发建构跨越空间边界的商业网络与非正式社会秩序。\n\n多年深度田野调查结合中国民间关系网络与空间政治分析。\n\n民间社会具有强大的自我组织能力；移民社区的生存逻辑挑战了以国家为中心的发展与管治叙事。",
    "location": "Beijing, Zhejiangcun",
    "countryOrRegion": "China",
    "lat": 39.9042,
    "lon": 116.4074,
    "sourceField": "中国 - 北京浙江村",
    "locationEn": "China·Beijing, Zhejiangcun"
  },
  {
    "id": "ethnography-43",
    "title": "《治理教育欲望》(Governing Educational Desire)",
    "year": 2011,
    "author": "Andrew Kipnis（任柯安）",
    "publisher": "University of Chicago Press",
    "summary": "山东邹平的学生、家长与教师如何被国家与市场共同塑造出对教育成功的强烈渴望与自我规训冲动。\n\n中学与家庭的长期民族志调查结合政策文本分析。\n\n教育欲望并非自然本能，而是通过治理技术被生产出来；国家政策与市场逻辑在个体的教育焦虑中深度汇合。",
    "location": "Shandong, Zouping",
    "countryOrRegion": "China",
    "lat": 36.8628,
    "lon": 117.742,
    "sourceField": "中国 - 山东邹平",
    "locationEn": "China·Shandong, Zouping"
  },
  {
    "id": "ethnography-44",
    "title": "《信用的宇宙论》(Cosmologies of Credit)",
    "year": 2010,
    "author": "Julie Y. Chu（朱苑瑜）",
    "publisher": "Duke University Press",
    "summary": "福州长乐村民如何在蛇头、神明与亲属债务的多重信用宇宙论中构建出走海外的强烈意志与生命项目。\n\n长乐村落长期田野调查，追踪\"出发\"而非\"抵达\"的移民图景。\n\n移民不仅是经济理性选择，更是嵌入神圣债务与本体论可能性的宇宙论实践；离开本身即是一种存在论变迁。",
    "location": "Fujian, Fuzhou",
    "countryOrRegion": "China",
    "lat": 26.0745,
    "lon": 119.2965,
    "sourceField": "中国 - 福建福州",
    "locationEn": "China·Fujian, Fuzhou"
  },
  {
    "id": "ethnography-45",
    "title": "《异质的世界化》(Other-Worldly)",
    "year": 2009,
    "author": "Mei Zhan（詹梅）",
    "publisher": "Duke University Press",
    "summary": "中医如何在上海与旧金山之间的跨国流通中，被重新组装为全球替代医学与中国现代性的双重象征。\n\n上海中医院与旧金山中医实践者的多点民族志调查。\n\n中医是\"异质世界化\"的产物，既非传统的遗存，也非西方的他者；其跨国流通揭示了现代性本身的多元路径。",
    "location": "Shanghai / USA - San Francisco",
    "countryOrRegion": "China",
    "lat": 31.2304,
    "lon": 121.4737,
    "sourceField": "中国 - 上海 / 美国 - 旧金山",
    "locationEn": "China·Shanghai / USA·San Francisco",
    "sites": [
      {
        "lat": 31.2304,
        "lon": 121.4737
      },
      {
        "lat": 37.7749,
        "lon": -122.4194
      }
    ]
  },
  {
    "id": "ethnography-46",
    "title": "《不确定的爱》(Love's Uncertainty)",
    "year": 2015,
    "author": "Teresa Kuan（关宜馨）",
    "publisher": "University of California Press",
    "summary": "昆明城市中产家庭如何在\"提升人口素质\"的国家话语下，调和爱的伦理理想与激烈教育竞争的现实压力。\n\n城市家庭长期民族志调查，结合育儿手册、电视剧及政策文本的综合分析。\n\n爱的实践深嵌于国家话语与个人伦理的张力之中。",
    "location": "Yunnan, Kunming",
    "countryOrRegion": "China",
    "lat": 25.0389,
    "lon": 102.7183,
    "sourceField": "中国 - 云南昆明",
    "locationEn": "China·Yunnan, Kunming"
  },
  {
    "id": "ethnography-47",
    "title": "《当代中国农村的卫生、社会性和文化》(Hygiene, Sociality, and Culture in Contemporary Rural China)",
    "year": 2016,
    "author": "Lili Lai（赖立里）",
    "publisher": "Amsterdam University Press",
    "summary": "\"新农村\"改造运动将\"卫生\"建构为衡量农村现代化程度的核心标准，并以此再生产城乡等级。\n\n河南农村长期田野调查结合政策文本与地方日常实践分析。\n\n卫生话语将农村贫困归因于农民的文化落后，掩盖了结构性不平等；国家治理的责任被转嫁为个体卫生习惯的道德问题。",
    "location": "Henan Province, Rural Villages",
    "countryOrRegion": "China",
    "lat": 34.7657,
    "lon": 113.7536,
    "sourceField": "中国 - 河南农村",
    "locationEn": "China·Henan Province, Rural Villages"
  },
  {
    "id": "ethnography-48",
    "title": "《世界中心的贫民窟》(Ghetto at the Center of the World)",
    "year": 2011,
    "author": "Gordon Mathews（麥高登）",
    "publisher": "University of Chicago Press",
    "summary": "重庆大厦作为世界各地低端全球化贸易商（南亚、非洲商人）聚集的多族裔生存空间与非正式经济节点。\n\n建筑内多语种长期参与观察与网络贸易链追踪。\n\n低端全球化是全球资本主义的另一面；重庆大厦揭示主权边界之间的非正式跨国流通秩序。",
    "location": "Hong Kong, Chungking Mansions",
    "countryOrRegion": "China",
    "lat": 22.2964,
    "lon": 114.1722,
    "sourceField": "中国 - 香港重庆大厦",
    "locationEn": "China·Hong Kong, Chungking Mansions"
  },
  {
    "id": "ethnography-50",
    "title": "《灵魂的障碍》(A Disability of the Soul)",
    "year": 2013,
    "author": "Karen Nakamura",
    "publisher": "Cornell University Press",
    "summary": "日本北海道浦河町\"Bethel House\"——一个由精神分裂症患者自主管理的另类社区——中成员的日常生活与集体身份认同。\n\n社区长期参与观察，结合生命故事访谈与两部纪录片的视觉民族志。\n\n精神疾病是社会与文化的构建；Bethel House 的社区康复模式展示了去机构化与病患自我赋权的另一种可能。",
    "location": "Hokkaido, Urakawa, Bethel House",
    "countryOrRegion": "Japan",
    "lat": 43.42,
    "lon": 142.78,
    "sourceField": "日本 - 北海道浦河町",
    "locationEn": "Japan·Hokkaido, Urakawa, Bethel House"
  },
  {
    "id": "ethnography-51",
    "title": "《日本的抑郁症》(Depression in Japan)",
    "year": 2012,
    "author": "Junko Kitanaka（北中淳子）",
    "publisher": "Princeton University Press",
    "summary": "日本职场文化与精神病学话语如何共同将抑郁症建构为一种社会性苦难，进而引发大规模诊断与用药热潮。\n\n精神科诊所与职场田野调查结合精神病学史与药物推广档案分析。\n\n抑郁症在日本的流行不仅是医学事件，更是社会危机的症候；精神病学的扩张重塑了日本人对工作、苦难与自我的理解。",
    "location": "Tokyo",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京",
    "locationEn": "Japan·Tokyo"
  },
  {
    "id": "ethnography-52",
    "title": "《筑地》(Tsukiji)",
    "year": 2004,
    "author": "Theodore C. Bestor",
    "publisher": "University of California Press",
    "summary": "东京筑地鱼市场作为世界最大海鲜交易枢纽，其商人文化、拍卖仪式与全球商品链的运作逻辑。\n\n市场长期参与观察，结合商人网络访谈与全球金枪鱼贸易链追踪。\n\n筑地不仅是经济场所，更是日本商人传统与全球资本主义相互嵌套的文化节点；地方饮食文化通过市场参与全球化进程。",
    "location": "Tokyo, Tsukiji Market",
    "countryOrRegion": "Japan",
    "lat": 35.6655,
    "lon": 139.7707,
    "sourceField": "日本 - 东京筑地市场",
    "locationEn": "Japan·Tokyo, Tsukiji Market"
  },
  {
    "id": "ethnography-53",
    "title": "《治愈劳动》(Healing Labor)",
    "year": 2020,
    "author": "Gabriele Koch",
    "publisher": "Stanford University Press",
    "summary": "东京性产业中的日本女性从业者如何将性工作理解为一种女性化的照护劳动，并在此框架中构建职业认同。\n\n与东京性工作者长期田野访谈，结合日本性别劳动政治经济学分析。\n\n性被女性从业者理解为维系男性身心健康的\"治愈劳动\"；这一框架揭示性别化劳动分工与日本经济体制之间的深层连接。",
    "location": "Tokyo",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京",
    "locationEn": "Japan·Tokyo"
  },
  {
    "id": "ethnography-54",
    "title": "《千禧年的怪物》(Millennial Monsters)",
    "year": 2006,
    "author": "Anne Allison",
    "publisher": "University of California Press",
    "summary": "日本电子游戏、动漫与玩具如何在全球流通中将日本\"酷文化\"建构为新型帝国软实力与商品拜物教。\n\n玩具产业、消费者文化与全球营销实践的多点民族志研究。\n\n\"神奇宝贝\"等怪兽商品将孤独与技术焦虑转化为消费欲望；日本流行文化在全球化中构建了一种千禧年资本主义的新型主体。",
    "location": "Tokyo (& Global Markets)",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京（及全球市场）",
    "locationEn": "Japan·Tokyo (& Global Markets)"
  },
  {
    "id": "ethnography-55",
    "title": "《亲密的分离》(Intimate Disconnections)",
    "year": 2020,
    "author": "Allison Alexy",
    "publisher": "University of Chicago Press",
    "summary": "当代日本离婚率上升背景下，离婚者——尤其是女性——如何将离婚重新叙述为寻求自主与个人成长的积极选择。\n\n东京离婚者的长期访谈与日本婚姻咨询机构田野调查。\n\n离婚在日本从道德失败被重新框架为个体独立的浪漫叙事；这一转变折射出新自由主义情感政治对私人生活的深层渗透。",
    "location": "Tokyo",
    "countryOrRegion": "Japan",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京",
    "locationEn": "Japan·Tokyo"
  },
  {
    "id": "ethnography-56",
    "title": "《被收养的领地》(Adopted Territory)",
    "year": 2010,
    "author": "Eleana Kim",
    "publisher": "Duke University Press",
    "summary": "跨国韩裔领养者如何在韩国官方民族主义与西方领养家庭之间协商归属感与身份认同。\n\n首尔\"寻根之旅\"项目与海外韩裔领养者社群的多点民族志调查。\n\n跨国领养将儿童卷入国家民族主义、种族政治与全球化情感市场；领养者的\"被领养领地\"揭示公民身份与血缘归属的内在矛盾。",
    "location": "Seoul (& Overseas Korean Adoptee Communities)",
    "countryOrRegion": "South Korea",
    "lat": 37.5665,
    "lon": 126.978,
    "sourceField": "韩国 - 首尔（及海外韩裔领养者社群）",
    "locationEn": "South Korea·Seoul (& Overseas Korean Adoptee Communities)"
  },
  {
    "id": "ethnography-57",
    "title": "《债务危机中的韩国人》(South Koreans in the Debt Crisis)",
    "year": 2009,
    "author": "Jesook Song",
    "publisher": "Duke University Press",
    "summary": "1997年亚洲金融危机后，韩国国家如何通过重构失业、福利与家庭话语，将新自由主义逻辑内化为公民美德。\n\n首尔政府福利机构与无家可归者安置点的田野调查结合政策文本分析。\n\n债务危机催生了新型\"新自由主义福利社会\"；国家将经济失败归咎于个体，而非结构性不平等，将自我管理转化为爱国责任。",
    "location": "Seoul",
    "countryOrRegion": "South Korea",
    "lat": 37.5665,
    "lon": 126.978,
    "sourceField": "韩国 - 首尔",
    "locationEn": "South Korea·Seoul"
  },
  {
    "id": "ethnography-58",
    "title": "《为爱而行》(On the Move for Love)",
    "year": 2010,
    "author": "Sealing Cheng（鄭詩靈）",
    "publisher": "University of Pennsylvania Press",
    "summary": "菲律宾女性娱乐工作者如何在韩国美军基地周边的基地村中，在合法边界与情感劳动之间寻求尊严与出路。\n\n基地村长期参与观察与菲律宾女性工作者深度访谈。\n\n情感劳动与性工作在军事驻留的地缘政治框架下被性别化与种族化；女性的迁移不仅是经济决策，更是爱与主体性的实践。",
    "location": "Dongducheon, US Military Camptown",
    "countryOrRegion": "South Korea",
    "lat": 37.9036,
    "lon": 127.0606,
    "sourceField": "韩国 - 东豆川 美军基地周边",
    "locationEn": "South Korea·Dongducheon, US Military Camptown"
  },
  {
    "id": "ethnography-59",
    "title": "《野鬼的时代》(The Age of Wild Ghosts)",
    "year": 2001,
    "author": "Erick Mueggler",
    "publisher": "University of California Press",
    "summary": "云南彝族村民如何通过仪式与鬼魂叙事，应对遗留的创伤记忆。\n\n长期村落田野调查，结合仪式文本与口述史。\n\n历史暴力以鬼魂的形式栖居于地景之中；暴力的记忆只能在国家叙事之外的仪式领域中被迂回表达与处理。",
    "location": "Yunnan, Yi People (Lufeng County)",
    "countryOrRegion": "China",
    "lat": 25.15,
    "lon": 102.08,
    "sourceField": "中国 - 云南彝族（禄丰县）",
    "locationEn": "China·Yunnan, Yi People (Lufeng County)"
  },
  {
    "id": "ethnography-60",
    "title": "《纸路》(The Paper Road)",
    "year": 2011,
    "author": "Erick Mueggler",
    "publisher": "University of California Press",
    "summary": "十九至二十世纪西方植物学家在云南与西藏的采集活动，如何在档案、标本与地方记忆中留下相互矛盾的痕迹。\n\n档案研究与沿原路线的当代民族志重走相结合。\n\n博物学档案是帝国知识生产的遗留物；将档案与身体经验并置，揭示科学探索的多重时间性与殖民暴力。",
    "location": "Yunnan / Tibet (Botanical Expedition Routes)",
    "countryOrRegion": "China",
    "lat": 29.65,
    "lon": 91.1,
    "sourceField": "中国 - 云南 / 西藏",
    "locationEn": "China·Yunnan / Tibet (Botanical Expedition Routes)"
  },
  {
    "id": "ethnography-61",
    "title": "《逝者悼歌》(Songs for Dead Parents)",
    "year": 2017,
    "author": "Erick Mueggler",
    "publisher": "University of Chicago Press",
    "summary": "彝族丧礼中吟诵的哀歌如何在文本、尸体与宇宙秩序之间构建死亡与过渡的意义。\n\n丧礼仪式的长期参与观察与仪式文本的语言学精读分析。\n\n语言不只是描述世界，而是在仪式表演中主动制造新的存在形态；哀歌的表演性言说重组了人、鬼与神的关系格局。",
    "location": "Yunnan, Yi People (Lufeng County)",
    "countryOrRegion": "China",
    "lat": 25.15,
    "lon": 102.08,
    "sourceField": "中国 - 云南彝族（禄丰县）",
    "locationEn": "China·Yunnan, Yi People (Lufeng County)"
  },
  {
    "id": "ethnography-62",
    "title": "《我的凉山兄弟》(Passage to Manhood)",
    "year": 2011,
    "author": "Shao-hua Liu（劉紹華）",
    "publisher": "Stanford University Press",
    "summary": "凉山彝族（诺苏）青年男性如何在改革开放后的流动与城乡落差中，陷入海洛因成瘾与艾滋病的双重困境。\n\n凉山彝族社区长期田野调查，追踪青年迁徙轨迹与吸毒网络。\n\n成瘾不是道德失败，而是现代化进程中少数民族青年被边缘化的结构性后果；国家防艾项目未能触及成瘾的社会根源。",
    "location": "Sichuan, Liangshan Yi (Nuosu) Territory",
    "countryOrRegion": "China",
    "lat": 27.8945,
    "lon": 102.2644,
    "sourceField": "中国 - 四川省 凉山 彝族（诺苏）地区",
    "locationEn": "China·Sichuan, Liangshan Yi (Nuosu) Territory"
  },
  {
    "id": "ethnography-64",
    "title": "《勉族关系》(Mien Relations)",
    "year": 2005,
    "author": "Hjorleifur Jonsson",
    "publisher": "Cornell University Press",
    "summary": "泰国清莱勉族如何在国家整合、发展计划与跨境离散网络中维持自身文化实践与社会关系。\n\n泰国北部山地长期田野调查，结合历史人口档案与跨境网络追踪。\n\n山地族群与低地国家的关系并非单向同化，而是持续的双向谈判；勉族的族群关系策略是一种有意识的主权协商实践。",
    "location": "Chiang Rai, Mien (Yao) Highland Communities",
    "countryOrRegion": "Thailand",
    "lat": 19.9105,
    "lon": 99.8406,
    "sourceField": "泰国 - 清莱省勉（瑶）族山地社区",
    "locationEn": "Thailand·Chiang Rai, Mien (Yao) Highland Communities"
  },
  {
    "id": "ethnography-65",
    "title": "《他者之社会》(Society of Others)",
    "year": 2009,
    "author": "Rupert Stasch",
    "publisher": "University of California Press",
    "summary": "科罗瓦伊人如何将\"他异性\"作为社会关系的核心原则，通过陌生感构建亲属与哀悼的意义。\n\n两年深度田野调查，结合语言学与仪式分析。\n\n社会关系的基础不是同一性而是差异；美拉尼西亚社会的他者关系理论对西方人类学亲属理论构成根本性挑战。",
    "location": "West Papua, Korowai Territory (Melanesia)",
    "countryOrRegion": "Indonesia",
    "lat": -5.55,
    "lon": 140.45,
    "sourceField": "印度尼西亚 - 西巴布亚科罗瓦伊地区",
    "locationEn": "Indonesia·West Papua, Korowai Territory (Melanesia)"
  },
  {
    "id": "ethnography-67",
    "title": "《逆向人类学》(Reverse Anthropology)",
    "year": 2006,
    "author": "Stuart Kirsch",
    "publisher": "Stanford University Press",
    "summary": "奥克特迪铜矿污染引发的原住民环境运动，以及原住民如何以自身分析框架理解和应对采矿资本主义。\n\n长期田野调查结合法律诉讼档案与环境运动跟踪。\n\n原住民社会分析具有独立的认识论效力；\"逆向人类学\"要求研究者承认被研究者同样在分析我们的世界。",
    "location": "Ok Tedi Mining Area (Melanesia)",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.27,
    "lon": 141.23,
    "sourceField": "巴布亚新几内亚 - 西巴布亚奥克特迪矿区",
    "locationEn": "Papua New Guinea·Ok Tedi Mining Area (Melanesia)"
  },
  {
    "id": "ethnography-68",
    "title": "《在全球的边缘》(On the Edge of the Global)",
    "year": 2011,
    "author": "Niko Besnier",
    "publisher": "Stanford University Press",
    "summary": "汤加人在全球化、移民压力与本土身份认同之间产生的现代性焦虑与道德危机感。\n\n汤加群岛多社区田野调查，结合海外侨民网络与媒体研究。\n\n太平洋岛民并非全球化的被动接受者，而是在移动与根植之间艰难维持主体性的现代主体；焦虑本身是结构性的。",
    "location": "Tongan Islands (Polynesia)",
    "countryOrRegion": "Tonga",
    "lat": -21.18,
    "lon": -175.2,
    "sourceField": "汤加 - 汤加群岛",
    "locationEn": "Tonga·Tongan Islands (Polynesia)"
  },
  {
    "id": "ethnography-69",
    "title": "《金矿上的利维坦》(Leviathans at the Gold Mine)",
    "year": 2014,
    "author": "Alex Golub",
    "publisher": "Duke University Press",
    "summary": "巴布亚新几内亚伊皮利人与跨国金矿公司如何在谈判、冲突与法律程序中相互塑造对方的主体形态。\n\n矿区长期田野调查结合企业文件与法律档案分析。\n\n公司与原住民群体都不是预先存在的固定实体，而是在资源开发的政治过程中相互构成的行动者。",
    "location": "Porgera Gold Mine, Ipili People (Melanesia)",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.46,
    "lon": 143.12,
    "sourceField": "巴布亚新几内亚 - 波尔盖拉金矿区",
    "locationEn": "Papua New Guinea·Porgera Gold Mine, Ipili People (Melanesia)"
  },
  {
    "id": "ethnography-70",
    "title": "《礼物的性别》(The Gender of the Gift)",
    "year": 1988,
    "author": "Marilyn Strathern",
    "publisher": "University of California Press",
    "summary": "美拉尼西亚社会中礼物交换的性别逻辑：女性并非交换的主体，而是被纳入男性礼物网络的媒介与对象。\n\n跨美拉尼西亚比较民族志与象征人类学理论综合分析。\n\n\"礼物\"范畴不能被移植于美拉尼西亚；性别在此不是社会身份，而是关系转换的媒介。",
    "location": "Melanesian Highlands (Mt. Hagen Area)",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.86,
    "lon": 144.23,
    "sourceField": "巴布亚新几内亚 - 美拉尼西亚高地（哈根山区）",
    "locationEn": "Papua New Guinea·Melanesian Highlands (Mt. Hagen Area)"
  },
  {
    "id": "ethnography-71",
    "title": "《廉价的肉》(Cheap Meat)",
    "year": 2010,
    "author": "D. Gewertz & F. Errington",
    "publisher": "University of California Press",
    "summary": "廉价羊排边角料（flap）从澳新生产商到太平洋岛国消费者之间的商品链，以及其如何加剧当地肥胖与健康危机。\n\n多点商品链民族志，追踪廉价肉类从生产、出口到消费的全程。\n\n全球食品贸易中的不平等并非偶然：富国的边角废料以\"廉价\"之名转化为穷国的饮食主流，将结构性暴力铭刻于身体之中。",
    "location": "Papua New Guinea / Tonga etc.",
    "countryOrRegion": "Pacific Island Nations",
    "lat": -21.18,
    "lon": -175.2,
    "sourceField": "太平洋岛国 - 巴布亚新几内亚/斐济/汤加",
    "locationEn": "Pacific Island Nations·Papua New Guinea / Tonga etc.",
    "sites": [
      {
        "lat": -9.4438,
        "lon": 147.1803
      },
      {
        "lat": -18.1248,
        "lon": 178.4501
      },
      {
        "lat": -21.18,
        "lon": -175.2
      }
    ]
  },
  {
    "id": "ethnography-72",
    "title": "《一切曾是永恒，直到它不复存在》(Everything Was Forever, Until It Was No More)",
    "year": 2006,
    "author": "Alexei Yurchak",
    "publisher": "Princeton University Press",
    "summary": "晚期苏联日常生活中意识形态的\"超规范化\"悖论：人们既不真正相信也不公开反对，而是在表演性服从中开辟出意义丰沛的私人与公共世界。 列宁格勒、莫斯科及前苏联多地的生命叙事采集与党政档案研究。  苏联的崩溃对所有人而言都是意外；晚期社会主义的表演性逻辑挑战了关于权力、服从与抵抗的简单二元对立，深刻影响了后苏联研究与政治人类学。",
    "location": "Leningrad / Moscow",
    "countryOrRegion": "Russia / Soviet Union",
    "lat": 59.9343,
    "lon": 30.3351,
    "sourceField": "俄罗斯/苏联 - 列宁格勒·莫斯科",
    "locationEn": "Russia / Soviet Union·Leningrad / Moscow"
  },
  {
    "id": "ethnography-73",
    "title": "《梦境攸关》(Dreams that Matter)",
    "year": 2011,
    "author": "Amira Mittermaier",
    "publisher": "University of California Press",
    "summary": "开罗穆斯林的梦境实践：梦被理解为真主的传达，并被积极诠释、分享与付诸行动，构成一种独特的伊斯兰想象地理与日常宗教伦理。\n\n开罗多处清真寺、苏菲道堂与梦境诠释圈子的长期参与观察，结合梦境叙事的话语分析与伊斯兰梦境诠释传统文献研究。\n\n梦境不是心理学意义上的潜意识，而是嵌入神圣知识论的宗教认识论实践；通过梦境研究，挑战了世俗现代性关于主体性与想象力的标准假设。",
    "location": "Cairo",
    "countryOrRegion": "Egypt",
    "lat": 30.0444,
    "lon": 31.2357,
    "sourceField": "埃及 - 开罗",
    "locationEn": "Egypt·Cairo"
  },
  {
    "id": "ethnography-74",
    "title": "《道德新自由主义者》(The Moral Neoliberal)",
    "year": 2012,
    "author": "Andrea Muehlebach",
    "publisher": "University of Chicago Press",
    "summary": "意大利北部新自由主义福利重构后，国家如何将公民无偿志愿劳动道德化，将情感与善意转化为新的治理资源以替代公共服务。  米兰及伦巴第多处志愿组织的长期参与田野调查，结合福利政策文本与道德话语分析。  情感与道德并非新自由主义的对立面，而是其核心生产力；志愿主义将政治经济问题转化为个体美德问题，为福利国家收缩提供道德合法性。",
    "location": "Lombardy (Greater Milan)",
    "countryOrRegion": "Italy",
    "lat": 45.4642,
    "lon": 9.19,
    "sourceField": "意大利 - 伦巴第大区（米兰周边）",
    "locationEn": "Italy·Lombardy (Greater Milan)"
  },
  {
    "id": "ethnography-75",
    "title": "《摩擦》(Friction)",
    "year": 2004,
    "author": "Anna Tsing（罗安清）",
    "publisher": "Princeton University Press",
    "summary": "追踪印度尼西亚加里曼丹热带雨林中，环保运动、伐木资本与国家权力在全球接触地带相互激烈碰撞的过程。\n\n多地点田野调查，结合对激进主义者、伐木工人、地方原住民社区及国际NGO的长期深度访谈与参与观察。\n\n\"全球化\"并非无摩擦的普遍流动，而是在差异与不均等相遇中被具体制造出来；摩擦既是破坏力量，也是变革的动能。",
    "location": "Kalimantan (Borneo)",
    "countryOrRegion": "Indonesia",
    "lat": -0.7893,
    "lon": 113.9213,
    "sourceField": "印度尼西亚 - 加里曼丹（婆罗洲）",
    "locationEn": "Indonesia·Kalimantan (Borneo)"
  },
  {
    "id": "ethnography-76",
    "title": "《曼谷的亲密经济》(The Intimate Economies of Bangkok)",
    "year": 2004,
    "author": "Ara Wilson",
    "publisher": "University of California Press",
    "summary": "曼谷的直销网络、购物中心文化与性别异质性（tom/dee关系）如何在跨国资本主义流通中共同重塑泰国的亲密关系与性别秩序。\n\n曼谷多场景田野调查，涵盖雅芳女销售员、性别多元社群与大型商场从业者的深度访谈及参与观察。\n\n\"亲密性\"是全球资本主义的核心经济逻辑而非其对立面；泰国的性别多元性既是商品化的对象，也是抵抗同质化的文化资源。",
    "location": "Bangkok",
    "countryOrRegion": "Thailand",
    "lat": 13.7563,
    "lon": 100.5018,
    "sourceField": "泰国 - 曼谷",
    "locationEn": "Thailand·Bangkok"
  },
  {
    "id": "ethnography-77",
    "title": "《日常转变》(Everyday Conversions)",
    "year": 2017,
    "author": "Attiya Ahmad",
    "publisher": "Duke University Press",
    "summary": "科威特家庭中南亚穆斯林女性佣工的宗教实践与日常照护关系，深度挑战了移民劳工研究中将其化约为受剥削受害者的刻板叙事。\n\n科威特雇主家庭的长期参与观察与南亚女性移工深度访谈，结合海湾国家移民政策与伊斯兰伦理话语分析。\n\n皈依与宗教实践不是被动顺从，而是移民女性在约束性处境中构建道德主体性、与灵性自我的主动策略。",
    "location": "Kuwait City",
    "countryOrRegion": "Kuwait",
    "lat": 29.3759,
    "lon": 47.9774,
    "sourceField": "科威特 - 科威特城",
    "locationEn": "Kuwait·Kuwait City"
  },
  {
    "id": "ethnography-78",
    "title": "《全球\"猎身\"》(Global \"Body Shopping\")",
    "year": 2007,
    "author": "Biao Xiang（项飙）",
    "publisher": "Princeton University Press",
    "summary": "追踪印度IT劳动力通过中介在全球流通。\n\n南印度与澳大利亚多点田野调查。\n\n灵活的全球资本主义将印度IT工人纳入劳动调配机制；嫁妇、家庭网络与移民签证共同维系着新经济的弹性剥削结构。",
    "location": "India (Hyderabad) / Australia",
    "countryOrRegion": "India (Hyderabad) / Australia",
    "lat": 17.385,
    "lon": 78.4867,
    "sourceField": "印度 - 海得拉巴/ 澳大利亚",
    "locationEn": "India (Hyderabad) / Australia",
    "sites": [
      {
        "lat": 17.385,
        "lon": 78.4867
      },
      {
        "lat": -33.8688,
        "lon": 151.2093
      }
    ]
  },
  {
    "id": "ethnography-79",
    "title": "《对未来的乡愁》(Nostalgia for the Future)",
    "year": 2010,
    "author": "Charles Piot",
    "publisher": "University of Chicago Press",
    "summary": "冷战终结后多哥社会中，五旬节基督教运动、美国移民签证彩票与NGO治理如何共同重塑了卡布雷人的主体性与时间想象，制造出一种对冷战援助时代的反向乡愁。  洛美城市田野调查与卡布雷农村社区对比研究，历时逾三十年长期追踪。  后冷战非洲的\"未来\"是对过去的怀旧性重构；全球化并未带来进步，而是制造了匮乏感与对另一种现代性的切身渴望。",
    "location": "Lomé (& Rural Kabre Territory)",
    "countryOrRegion": "Togo",
    "lat": 6.1725,
    "lon": 1.2314,
    "sourceField": "多哥 - 洛美（及农村卡布雷族地区）",
    "locationEn": "Togo·Lomé (& Rural Kabre Territory)"
  },
  {
    "id": "ethnography-80",
    "title": "《声音社会主义》(Sonic Socialism)",
    "year": 2025,
    "author": "Christina Schwenkel",
    "publisher": "University of California Press",
    "summary": "新冠疫情期间，越南河内的广播喇叭、即时通讯与公共卫生视频等声音技术如何成为社会主义国家动员民众、编织照护与管控的关键基础设施。\n\n以\"声音田野调查\"（soundwork）为核心的感官自传民族志，追踪2020年疫情第一年的隔离、封控与日常声音景观。\n\n声音治理将听觉实践转化为国家权力的延伸；社会主义照护伦理在声音空间中同时编织了连接与控制的双重网络。",
    "location": "Hanoi",
    "countryOrRegion": "Vietnam",
    "lat": 21.0278,
    "lon": 105.8342,
    "sourceField": "越南 - 河内",
    "locationEn": "Vietnam·Hanoi"
  },
  {
    "id": "ethnography-81",
    "title": "《战争机器》(The War Machines)",
    "year": 2011,
    "author": "Danny Hoffman",
    "publisher": "Duke University Press",
    "summary": "塞拉利昂与利比里亚年轻男性如何被整合进一套超越国界的战争机器，以劳动力的形式被资本、军阀与国际人道主义机构反复调度与丢弃。  战时军营与战后城市的长期田野调查，结合武装派系网络与援助机构运作的双线追踪。  西非战争的逻辑不是族群仇恨，而是一种去个体化的生命政治；年轻人在战争机器中既非施害者也非受害者，而是可被替换的劳动单元。",
    "location": "Wartime Camps & Postwar Cities",
    "countryOrRegion": "Sierra Leone / Liberia",
    "lat": 8.484,
    "lon": -13.2299,
    "sourceField": "塞拉利昂·利比里亚 - 战时军营与战后城市",
    "locationEn": "Sierra Leone / Liberia·Wartime Camps & Postwar Cities",
    "sites": [
      {
        "lat": 8.484,
        "lon": -13.2299
      },
      {
        "lat": 6.3156,
        "lon": -10.8074
      }
    ]
  },
  {
    "id": "ethnography-82",
    "title": "《当身体记忆时》(When Bodies Remember)",
    "year": 2007,
    "author": "Didier Fassin",
    "publisher": "University of California Press",
    "summary": "南非艾滋病危机中，种族隔离的历史创伤如何通过身体被铭刻并激活，塑造了南非政府与民众对HIV/AIDS的独特认知、政策回应与拒绝科学的逻辑。  约翰内斯堡及多省田野调查，结合种族隔离历史档案与公共卫生政策的跨学科分析。  身体是历史的记忆库；南非艾滋病否认主义的政治逻辑只有在种族隔离创伤、与后殖民主权焦虑的双重背景下才可理解。",
    "location": "Johannesburg (& Eastern Cape / KwaZulu-Natal)",
    "countryOrRegion": "South Africa",
    "lat": -26.2041,
    "lon": 28.0473,
    "sourceField": "南非 - 约翰内斯堡（及东开普、夸祖鲁-纳塔尔省）",
    "locationEn": "South Africa·Johannesburg (& Eastern Cape / KwaZulu-Natal)"
  },
  {
    "id": "ethnography-83",
    "title": "《维持秩序》(Enforcing Order)",
    "year": 2013,
    "author": "Didier Fassin",
    "publisher": "Polity Press",
    "summary": "法国巴黎郊区警察日常执法实践的民族志：警察的种族化凝视、即兴暴力与对移民青年的系统性羞辱如何构成国家权力的微观运作机制。 随反巡逻队进行长期深度参与式田野调查，记录执法现场的即时决策与身体对抗。  执法行为不是法律的中性执行，而是种族化权威的日常再生产；警察的身体实践将阶级与族裔不平等铭刻于城市空间，揭示法治话语背后的道德双重标准。",
    "location": "Paris Banlieues",
    "countryOrRegion": "France",
    "lat": 48.901,
    "lon": 2.45,
    "sourceField": "法国 - 巴黎郊区（班利厄）",
    "locationEn": "France·Paris Banlieues"
  },
  {
    "id": "ethnography-84",
    "title": "《金沙萨》(Kinshasa)",
    "year": 2004,
    "author": "Filip De Boeck & Marie-Françoise Plissart",
    "publisher": "Ludion",
    "summary": "金沙萨日常生活的时间层叠、宗教想象与城市空间的不可见性：这座拒绝被西方城市理论化约的非洲大都市如何在国家失序中生产出另类的都市性。  金沙萨多地长期民族志田野调查，结合黑白摄影、儿童绘画与城市建筑的视觉民族志分析。  金沙萨的\"不可见\"城市性与\"第二世界\"宗教想象共同构成了一种另类都市现代性，开创了视觉民族志与城市理论跨界的写作范式。",
    "location": "Kinshasa",
    "countryOrRegion": "DRC",
    "lat": -4.4419,
    "lon": 15.2663,
    "sourceField": "刚果民主共和国 - 金沙萨",
    "locationEn": "DRC·Kinshasa"
  },
  {
    "id": "ethnography-86",
    "title": "《敞坟之地》(The Land of Open Graves)",
    "year": 2015,
    "author": "Jason De Léon",
    "publisher": "University of California Press",
    "summary": "以政策民族志与考古学、取证方法结合，揭示美国的边境政策如何将索诺拉沙漠变为无证移民的坟场。\n\n多年跟踪田野结合幸存者访谈与对遗留物品的物质分析。\n\n美国边境政策将死亡转嫁给沙漠和非人类行动者，掩盖了边境政策的系统性暴力。",
    "location": "Mexico (Sonora)",
    "countryOrRegion": "USA (Arizona)",
    "lat": 31.3322,
    "lon": -110.9378,
    "sourceField": "美国（亚利桑那州）- 墨西哥（索诺拉州）",
    "locationEn": "USA (Arizona)·Mexico (Sonora)"
  },
  {
    "id": "ethnography-87",
    "title": "《革命之后》(After the Revolution)",
    "year": 2014,
    "author": "Jessica Greenberg",
    "publisher": "Cornell University Press",
    "summary": "后米洛舍维奇时代，塞尔维亚学生运动如何在\"公民社会\"话语的包裹下，将政治激情转化为NGO化的温顺参与形式。  贝尔格莱德学生组织与青年活动人士的长期田野调查，结合公民教育材料与国际民主援助话语分析。  \"公民社会\"不是中立政治空间，塞尔维亚青年的政治想象在被规范化的过程中，也在夹缝中生长出本土的批判主体性。",
    "location": "Belgrade",
    "countryOrRegion": "Serbia",
    "lat": 44.7866,
    "lon": 20.4489,
    "sourceField": "塞尔维亚 - 贝尔格莱德",
    "locationEn": "Serbia·Belgrade"
  },
  {
    "id": "ethnography-89",
    "title": "《流动性的焦虑》(The Anxieties of Mobility)",
    "year": 2009,
    "author": "Johan Lindquist",
    "publisher": "University of Minnesota Press",
    "summary": "新加坡对岸的印尼边境岛屿巴淡，如何在全球劳工迁移、性旅游与国家经济特区政策的交汇处成为一个充满情感张力与社会失序的\"焦虑空间\"。\n\n巴淡岛移民工人、性工作者、劳工中介与政府官员的多群体长期参与观察与深度访谈。\n\n全球化的流动性不是解放，而是制造了新型情感脆弱性；焦虑作为一种情动状态，揭示了移动劳动者在边境资本主义中被悬置的存在困境。",
    "location": "Batam (Riau Islands)",
    "countryOrRegion": "Indonesia",
    "lat": 1.1301,
    "lon": 104.0529,
    "sourceField": "印度尼西亚 - 巴淡岛（廖内群岛）",
    "locationEn": "Indonesia·Batam (Riau Islands)"
  },
  {
    "id": "ethnography-90",
    "title": "《剃光野兽》(Shaving the Beasts)",
    "year": 2020,
    "author": "John Hartigan Jr.",
    "publisher": "University of Minnesota Press",
    "summary": "西班牙加利西亚每年一度的\"rapa das bestas\"仪式中，野马被围捕剃毛的过程如何揭示其复杂的社会生活、情感联结与创伤后恢复力。  驻扎山地对马群进行跟踪参与观察，并记录54张黑白照片。  马匹并非仪式的被动客体，而是具有主体性的社会行动者；这部民族志开创了以非人类为主角的写作范式。",
    "location": "Galicia (Sabucedo Village)",
    "countryOrRegion": "Spain",
    "lat": 42.55,
    "lon": -8.42,
    "sourceField": "西班牙 - 加利西亚（萨布塞多村）",
    "locationEn": "Spain·Galicia (Sabucedo Village)"
  },
  {
    "id": "ethnography-91",
    "title": "《多元主义的清算》(The Reckoning of Pluralism)",
    "year": 2014,
    "author": "Kabir Tambar",
    "publisher": "Stanford University Press",
    "summary": "土耳其阿列维人如何在世俗民族主义国家的多元主义话语、与伊斯兰主义政治之间，协商本族群的宗教差异与公共承认。  伊斯坦布尔及安纳托利亚多处阿列维社区田野调查，结合话语历史与伊斯兰教法档案分析。  世俗多元主义并不中立；国家对少数宗教群体的\"承认\"以规范化为代价，将差异纳入管控框架，而非真正容纳他异性。",
    "location": "Istanbul (& Anatolian Alevi Communities)",
    "countryOrRegion": "Turkey",
    "lat": 41.0082,
    "lon": 28.9784,
    "sourceField": "土耳其 - 伊斯坦布尔（及安纳托利亚阿列维社区）",
    "locationEn": "Turkey·Istanbul (& Anatolian Alevi Communities)"
  },
  {
    "id": "ethnography-92",
    "title": "《消逝的公顷》(The Vanishing Hectare)",
    "year": 2003,
    "author": "Katherine Verdery",
    "publisher": "Cornell University Press",
    "summary": "后社会主义罗马尼亚农村的土地去集体化进程：历史产权的重建如何激活被压抑的记忆、催生新型社会冲突与国家权力的重新布局。  特兰西瓦尼亚村落多年田野调查，结合产权法律档案与地方精英网络分析。  财产是社会关系与时间性的交汇点而非简单经济权利；去集体化在\"归还土地\"的口号下制造了新的不平等与身份认同政治。",
    "location": "Transylvania (Aurel Vlaicu Village)",
    "countryOrRegion": "Romania",
    "lat": 45.91,
    "lon": 23.27,
    "sourceField": "罗马尼亚 - 特兰西瓦尼亚（奥雷尔·弗拉伊库村）",
    "locationEn": "Romania·Transylvania (Aurel Vlaicu Village)"
  },
  {
    "id": "ethnography-93",
    "title": "《附魅的现代》(An Enchanted Modern)",
    "year": 2006,
    "author": "Lara Deeb",
    "publisher": "Princeton University Press",
    "summary": "贝鲁特南郊什叶派穆斯林女性如何将公开虔诚实践与对现代性的渴望融合，形成独特的\"附魅主体\"——既非世俗自由主义，也非保守传统主义。  达希亚区女性宗教活动、纪念仪式与日常生活的长期民族志调查。  现代性与宗教虔诚并非天然对立；什叶派女性通过公开表演的虔诚，在伊斯兰框架内争取主体性，有力挑战了西方女性主义对能动性的狭隘预设。",
    "location": "Beirut, Southern Suburbs (Dahiyya)",
    "countryOrRegion": "Lebanon",
    "lat": 33.85,
    "lon": 35.52,
    "sourceField": "黎巴嫩 - 贝鲁特南郊（达希亚区）",
    "locationEn": "Lebanon·Beirut, Southern Suburbs (Dahiyya)"
  },
  {
    "id": "ethnography-94",
    "title": "《边缘视野》(Peripheral Visions)",
    "year": 2008,
    "author": "Lisa Wedeen",
    "publisher": "University of Chicago Press",
    "summary": "统一后的也门如何在嚼卡特（qat）聚会、媒体话语表演与部落政治的交织中，建构出脆弱而真实的民族国家想象与公民认同。\n\n萨那与哈德拉毛的多地点长期田野调查，结合媒体话语分析与公共政治表演的细密观察。\n\n\"也门人\"的身份认同是表演性建构而非历史给定；边缘性使也门成为审视现代国家、民族主义与公共空间理论的独特棱镜。",
    "location": "Sanaa / Hadramawt",
    "countryOrRegion": "Yemen",
    "lat": 15.3694,
    "lon": 44.191,
    "sourceField": "也门 - 萨那·哈德拉毛",
    "locationEn": "Yemen·Sanaa / Hadramawt"
  },
  {
    "id": "ethnography-95",
    "title": "《边境工作》(Border Work)",
    "year": 2014,
    "author": "Madeline Reeves",
    "publisher": "Cornell University Press",
    "summary": "中亚三国交界费尔干纳盆地山地社区中，苏联划定的边境线如何在日常生活中被体验、逾越与重塑，使抽象的国家主权成为具身的空间实践。\n\n边境村落长期驻点田野调查，结合苏联领土划分档案研究与边境管控现场的参与观察。\n\n后苏联领土政治将原本流通的生活世界割裂争议边界，通过边境居民的行走路线、身份证件与跨境日常生活积累而被具身化。",
    "location": "Kyrgyz-Tajik-Uzbek borderlands",
    "countryOrRegion": "Central Asia",
    "lat": 40.5,
    "lon": 71.0,
    "sourceField": "中亚 - 吉尔吉斯/塔吉克/乌兹别克三国边界区域",
    "locationEn": "Central Asia·Kyrgyz-Tajik-Uzbek borderlands"
  },
  {
    "id": "ethnography-96",
    "title": "《石油时代》(In the Time of Oil)",
    "year": 2010,
    "author": "Mandana Limbert",
    "publisher": "Cornell University Press",
    "summary": "阿曼内陆绿洲古城居民如何在石油繁荣与文化遗产保护的双重话语下体验时间：既向往发展，又渴望保存\"前石油时代\"的本真性。  巴赫拉小镇长期田野调查，结合阿曼国家现代化政策文本与伊斯兰时间观分析。  石油现代化制造了特定的时间性悖论：过去被理想化为本真，当下被体验为过渡，未来则充满不确定；发展叙事与伊斯兰虔诚、本土记忆的张力共同构成了海湾国家现代性的独特质地。",
    "location": "Bahla (Interior Oasis Town)",
    "countryOrRegion": "Oman",
    "lat": 22.967,
    "lon": 57.299,
    "sourceField": "阿曼 - 巴赫拉（内陆绿洲古城）",
    "locationEn": "Oman·Bahla (Interior Oasis Town)"
  },
  {
    "id": "ethnography-97",
    "title": "《事物之下》(The Underneath of Things)",
    "year": 2001,
    "author": "Mariane C. Ferme",
    "publisher": "University of California Press",
    "summary": "塞拉利昂门德族社会中，秘密、物质性与历史暴力如何在日常物品与身体实践中被编码、传递并长期隐伏。  博地区门德族社区长期参与田野调查，结合内战前后的物质文化与秘密结社仪式分析。  理解非洲暴力需穿透其表层，深入物质和仪式之下的知识传递逻辑。",
    "location": "Bo District (Mende People)",
    "countryOrRegion": "Sierra Leone",
    "lat": 7.956,
    "lon": -11.74,
    "sourceField": "塞拉利昂 - 博地区（门德族）",
    "locationEn": "Sierra Leone·Bo District (Mende People)"
  },
  {
    "id": "ethnography-98",
    "title": "《乌兹别克斯坦的新女性》(The New Woman in Uzbekistan)",
    "year": 2006,
    "author": "Marianne Kamp",
    "publisher": "University of Washington Press",
    "summary": "苏联在乌兹别克斯坦推行去面纱运动（hujum）的历史：国家如何将穆斯林女性身体作为现代化改造的战场，以及女性如何以多元方式主动回应这一强制性冲击。\n\n结合苏联国家档案、党政文件与当地女性深度口述史访谈的历史民族志研究，辅以当代费尔干纳社区田野调查。\n\n乌兹别克女性在苏联现代化进程中，同时是被塑造者与具有主动性的历史行动者，去面纱运动并不必然带来解放。",
    "location": "Fergana Valley",
    "countryOrRegion": "Uzbekistan",
    "lat": 40.3864,
    "lon": 71.7864,
    "sourceField": "乌兹别克斯坦 - 费尔干纳盆地",
    "locationEn": "Uzbekistan·Fergana Valley"
  },
  {
    "id": "ethnography-99",
    "title": "《被驱逐出永恒之城》(Evicted from Eternity)",
    "year": 2009,
    "author": "Michael Herzfeld",
    "publisher": "University of Chicago Press",
    "summary": "罗马历史中心蒙蒂街区的老居民，在遗产旅游与房地产开发双重压力下，被迫迁离的政治过程与文化记忆。  蒙蒂街区长期参与民族志，结合城市规划档案、居民生命叙事与文化遗产话语分析。  \"永恒之城\"的神话为驱逐提供了话语掩护；国家遗产机制与全球资本合谋，将历史建筑保护转化为系统性的驱逐工具。",
    "location": "Rome (Monti Historic Quarter)",
    "countryOrRegion": "Italy",
    "lat": 41.895,
    "lon": 12.492,
    "sourceField": "意大利 - 罗马（蒙蒂历史街区）",
    "locationEn": "Italy·Rome (Monti Historic Quarter)"
  },
  {
    "id": "ethnography-100",
    "title": "《伊斯兰现代性》(Islamic Modern)",
    "year": 2002,
    "author": "Michael Peletz",
    "publisher": "Princeton University Press",
    "summary": "马来西亚伊斯兰宗教法庭的日常运作如何在穆斯林身份、性别秩序与国家权力之间共同建构出一种特殊的\"伊斯兰现代性\"。\n\n霹雳州宗教法庭长期参与观察，结合法庭记录档案与法官、当事人的深度访谈。\n\n伊斯兰现代性并非传统的简单延续或西方现代性的他者，而是在法律实践与政治竞争中被主动建构的混合产物。",
    "location": "Perak / Negeri Sembilan",
    "countryOrRegion": "Malaysia",
    "lat": 4.399,
    "lon": 101.53,
    "sourceField": "马来西亚 - 霹雳州·森美兰州",
    "locationEn": "Malaysia·Perak / Negeri Sembilan"
  },
  {
    "id": "ethnography-101",
    "title": "《地面上的事实》(Facts on the Ground)",
    "year": 2001,
    "author": "Nadia Abu El-Haj",
    "publisher": "University of Chicago Press",
    "summary": "以色列考古学实践如何通过挖掘、命名与展示，系统性地将巴勒斯坦地景改写为犹太历史主权的物质证据与国家正当性的科学基础。\n\n以色列考古遗址、博物馆与学术机构的田野调查，结合殖民档案、考古学建制史与科学实践的民族志分析。\n\n考古学不是对过去的中性发现，而是在地面上政治性地制造历史事实的实践；领土主权通过科学知识与物质改造共同生产。",
    "location": "Israel / Palestine",
    "countryOrRegion": "Israel / Palestine",
    "lat": 31.77,
    "lon": 35.21,
    "sourceField": "以色列/巴勒斯坦",
    "locationEn": "Israel / Palestine",
    "sites": [
      {
        "lat": 31.7683,
        "lon": 35.2137
      },
      {
        "lat": 31.9038,
        "lon": 35.2034
      }
    ]
  },
  {
    "id": "ethnography-102",
    "title": "《巴扎政治》(Bazaar Politics)",
    "year": 2011,
    "author": "Noah Coburn",
    "publisher": "Stanford University Press",
    "summary": "后塔利班时代阿富汗陶器之乡伊斯塔利夫的地方政治：部族长老、民主选举与国际援助项目如何在一个制陶小镇中相互角力，重塑社区权力格局。\n\n伊斯塔利夫社区长期田野调查，结合选举观察、陶器工匠工作坊参与与国际援助机构运作的双线追踪。\n\n阿富汗的\"民主建设\"在地方政治的具体质地中，显现为对既有权威关系的再包装而非根本性变革。",
    "location": "Istalif (North of Kabul)",
    "countryOrRegion": "Afghanistan",
    "lat": 34.83,
    "lon": 69.08,
    "sourceField": "阿富汗 - 伊斯塔利夫（喀布尔以北）",
    "locationEn": "Afghanistan·Istalif (North of Kabul)"
  },
  {
    "id": "ethnography-103",
    "title": "《无法治理的生命》(Ungovernable Life)",
    "year": 2017,
    "author": "Omar Dewachi",
    "publisher": "Stanford University Press",
    "summary": "伊拉克从萨达姆时代到美国占领后，医疗基础设施的系统性瓦解如何塑造了医生与患者的流亡轨迹，并制造出一种新型的生命政治困境。\n\n巴格达与贝鲁特医疗机构的田野调查，结合流亡医生的生命叙事、战争医学史档案与后殖民公共卫生文献的跨学科分析。\n\n战争创造了\"治理不能\"的生命地带；医疗的崩溃不是政策失败，而是主权暴力的系统性工程，将伊拉克医生与患者共同抛入无法被照护的存在困境。",
    "location": "Baghdad / Lebanon - Beirut",
    "countryOrRegion": "Iraq",
    "lat": 33.3152,
    "lon": 44.3661,
    "sourceField": "伊拉克 - 巴格达·黎巴嫩 - 贝鲁特",
    "locationEn": "Iraq·Baghdad / Lebanon·Beirut",
    "sites": [
      {
        "lat": 33.3152,
        "lon": 44.3661
      },
      {
        "lat": 33.8938,
        "lon": 35.5018
      }
    ]
  },
  {
    "id": "ethnography-106",
    "title": "《归属的危险》(The Perils of Belonging)",
    "year": 2009,
    "author": "Peter Geschiere",
    "publisher": "University of Chicago Press",
    "summary": "非洲各地兴起的\"本土人优先\"政治运动如何以\"先来者\"为由将邻居、外来者乃至长期居民排斥为危险的他者，并与欧洲极右排外主义形成结构性呼应。  喀麦隆与科特迪瓦多地田野调查，结合欧洲本土主义的跨文化比较分析。  归属感是排斥感的另一面；本土性政治既是后殖民国家危机的症候，也是全球化焦虑在地方话语中的表达。",
    "location": "Cameroon / Côte d'Ivoire (& Europe comparative)",
    "countryOrRegion": "Cameroon / Côte d'Ivoire (& Europe comparative)",
    "lat": 3.848,
    "lon": 11.5021,
    "sourceField": "喀麦隆·科特迪瓦（及欧洲比较）",
    "locationEn": "Cameroon / Côte d'Ivoire (& Europe comparative)",
    "sites": [
      {
        "lat": 3.848,
        "lon": 11.5021
      },
      {
        "lat": 6.8276,
        "lon": -5.2893
      }
    ]
  },
  {
    "id": "ethnography-107",
    "title": "《驯鹿人》(The Reindeer People)",
    "year": 2005,
    "author": "Piers Vitebsky",
    "publisher": "Houghton Mifflin Harcourt",
    "summary": "西伯利亚埃文驯鹿牧民在苏联解体后的生存危机、萨满信仰复兴与人鹿关系的伦理重建。  随埃文人共同游牧多年的深度参与田野调查，结合苏联档案与口述史研究。  人与驯鹿通过日常照料与梦境建立灵性纽带；后苏联社会断裂被萨满宇宙观重新缝合，呈现出迥异于西方现代性的人与非人关系模式。",
    "location": "Siberia, Eveny (Evenki) Territory",
    "countryOrRegion": "Russia",
    "lat": 65.0,
    "lon": 145.0,
    "sourceField": "俄罗斯 - 西伯利亚 埃文基地区",
    "locationEn": "Russia·Siberia, Eveny (Evenki) Territory"
  },
  {
    "id": "ethnography-108",
    "title": "《奴隶贸易的记忆》(Memories of the Slave Trade)",
    "year": 2002,
    "author": "Rosalind Shaw",
    "publisher": "University of Chicago Press",
    "summary": "塞拉利昂泰姆内族如何通过占卜仪式、精灵信仰与夜间的身体实践，在无文字的历史想象中保存和加工大西洋奴隶贸易的集体创伤记忆。  北方省泰姆内社区长期参与田野调查，结合仪式录像、历史档案与认知人类学的综合分析。  历史不只是文字书写的；仪式是非洲社会处理集体创伤的认知与情感技术，奴隶贸易的记忆以感官与灵性的形式延续至今。",
    "location": "Northern Province (Temne People)",
    "countryOrRegion": "Sierra Leone",
    "lat": 9.0,
    "lon": -12.0,
    "sourceField": "塞拉利昂 - 北方省（泰姆内族）",
    "locationEn": "Sierra Leone·Northern Province (Temne People)"
  },
  {
    "id": "ethnography-109",
    "title": "《战争灵魂》(Warring Souls)",
    "year": 2006,
    "author": "Roxanne Varzi",
    "publisher": "Duke University Press",
    "summary": "伊朗伊斯兰革命后，国家通过电影、电视与殉道话语对青年主体性的系统塑造，以及年轻一代在官方信仰与内心怀疑之间的深层撕裂。\n\n德黑兰电影制作机构与青年群体的参与田野调查，结合伊朗战争电影、国家媒体话语与青年日常生活叙事的综合文本分析。\n\n革命叙事通过美学与情动技术将殉道精神铭刻于身体；当代伊朗青年既是国家意识形态的产物，也是在其内部生长出异质欲望的裂缝主体。",
    "location": "Tehran",
    "countryOrRegion": "Iran",
    "lat": 35.6892,
    "lon": 51.389,
    "sourceField": "伊朗 - 德黑兰",
    "locationEn": "Iran·Tehran"
  },
  {
    "id": "ethnography-110",
    "title": "《政治灵性》(Political Spiritualities)",
    "year": 2009,
    "author": "Ruth Marshall",
    "publisher": "University of Chicago Press",
    "summary": "尼日利亚五旬节运动如何在国家失序与经济崩溃的缝隙中，建立起一套平行的道德秩序、身份体系与主权逻辑。  拉各斯与伊巴丹五旬节教会的长期参与田野调查，结合神学文本与政治史分析。  五旬节主义不是对现代性的逃离，而是在彻底重组自我的基础上，对政治主权与公民身份的宗教性夺取与再发明。",
    "location": "Lagos / Ibadan",
    "countryOrRegion": "Nigeria",
    "lat": 6.5244,
    "lon": 3.3792,
    "sourceField": "尼日利亚 - 拉各斯·伊巴丹",
    "locationEn": "Nigeria·Lagos / Ibadan"
  },
  {
    "id": "ethnography-111",
    "title": "《废物围城》(Waste Siege)",
    "year": 2019,
    "author": "Sophia Stamatopoulou-Robbins",
    "publisher": "Stanford University Press",
    "summary": "巴勒斯坦西岸在以色列占领下，废物处理基础设施的慢性失能如何成为日常统治与生命政治的关键物质媒介。\n\n西岸多处社区、废物处理设施与国际援助机构的长期田野调查，结合技术治理文件与居民日常经验分析。\n\n废物不仅是污染，更是占领的物化形式；基础设施的系统性不运转揭示了被占领人群被系统性悬置的生存处境。",
    "location": "West Bank",
    "countryOrRegion": "Palestine",
    "lat": 31.9466,
    "lon": 35.3027,
    "sourceField": "巴勒斯坦 - 西岸",
    "locationEn": "Palestine·West Bank"
  },
  {
    "id": "ethnography-112",
    "title": "《等待中的渴望》(Yearnings in the Meantime)",
    "year": 2015,
    "author": "Stef Jansen",
    "publisher": "Berghahn Books",
    "summary": "萨拉热窝普通市民在战后漫长等待中对\"正常生活\"的渴望、对欧洲未来的向往，以及这种集体期盼本身如何成为后冲突国际治理的对象。  萨拉热窝公寓街区长期田野调查，结合公共话语与欧盟政策文本分析。  后冲突社会中对正常性的期待既是生存策略，也是国际干预机构借以延迟结构性问责的情感资源。",
    "location": "Sarajevo",
    "countryOrRegion": "Bosnia-Herzegovina",
    "lat": 43.8563,
    "lon": 18.4131,
    "sourceField": "波斯尼亚 - 萨拉热窝",
    "locationEn": "Bosnia-Herzegovina·Sarajevo"
  },
  {
    "id": "ethnography-113",
    "title": "《灵魂之结》(Knot of the Soul)",
    "year": 2018,
    "author": "Stefania Pandolfo",
    "publisher": "University of Chicago Press",
    "summary": "摩洛哥城市贫困青年同时遭受精神病学诊断与伊斯兰灵性治疗两套话语体系的拉锯，以及在这一张力中对自我、苦难与主体性的艰难重建。\n\n精神病院与传统治疗师（fqih）双线田野调查，结合精神分析理论文本、伊斯兰古典文献细读与患者深度叙事访谈。\n\n精神苦难是灵魂在历史暴力裂缝中寻找意义的挣扎；精神分析与伊斯兰话语在苦难主体的边界地带，形成难以调和却相互缠绕的知识角力。",
    "location": "Casablanca / Rabat",
    "countryOrRegion": "Morocco",
    "lat": 33.5731,
    "lon": -7.5898,
    "sourceField": "摩洛哥 - 卡萨布兰卡·拉巴特",
    "locationEn": "Morocco·Casablanca / Rabat"
  },
  {
    "id": "ethnography-115",
    "title": "《改善的意志》(The Will to Improve)",
    "year": 2007,
    "author": "Tania Murray Li",
    "publisher": "Duke University Press",
    "summary": "苏拉威西高地社区百余年间遭遇殖民治理、发展项目与国家干预的历史积累，以及\"改善\"话语反复失败的内在逻辑。\n\n结合深度档案研究、多地社区长期田野调查与福柯治理性理论的跨历史分析。\n\n\"改善\"话语将根本的政治问题技术化为可管理的项目，系统性地掩盖了权力与结构性不平等；发展干预在塑造治理主体的同时，也激发出土著社区的能动性与抵抗。",
    "location": "Sulawesi",
    "countryOrRegion": "Indonesia",
    "lat": -2.5489,
    "lon": 120.324,
    "sourceField": "印度尼西亚 - 苏拉威西",
    "locationEn": "Indonesia·Sulawesi"
  },
  {
    "id": "ethnography-116",
    "title": "《虚构的空间》(The Make-Believe Space)",
    "year": 2012,
    "author": "Yael Navaro-Yashin",
    "publisher": "Duke University Press",
    "summary": "土耳其控制下的北塞浦路斯居民如何在法律上不被国际承认的\"虚构\"政治实体中生活，以及这种持续的不真实感如何渗透进日常情感与物质世界。  北塞浦路斯多地田野调查，结合废弃希腊裔财产的物质文化分析与情感民族志。  政治暴力的后果以废墟与遗留物品的形式持续散发影响；情感并非仅是主观感受，而是在政治遗留物的物质性中被生产出来的，推动了人类学对情感与物质的理论化。",
    "location": "Cyprus (Northern/Turkish-Controlled Cyprus)",
    "countryOrRegion": "Cyprus (Northern/Turkish-Controlled Cyprus)",
    "lat": 35.1856,
    "lon": 33.3823,
    "sourceField": "塞浦路斯（北塞浦路斯/土耳其控制区）",
    "locationEn": "Cyprus (Northern / Turkish-Controlled Cyprus)"
  },
  {
    "id": "ethnography-117",
    "title": "《实验室生活》(Laboratory Life)",
    "year": 1986,
    "author": "Bruno Latour & Steve Woolgar",
    "publisher": "Princeton University Press",
    "summary": "追踪索尔克研究所神经内分泌实验室的日常工作，揭示科学事实如何通过社会活动、修辞与物质工具被建构出来。\n\n科学家实验室参与观察，结合对实验记录、论文草稿与办公室话语的细密分析。\n\n科学不是对客观自然的直接反映，而是被科学实践积极建构。",
    "location": "CA, Salk Institute",
    "countryOrRegion": "USA",
    "lat": 32.8877,
    "lon": -117.2448,
    "sourceField": "美国 - 加州 索尔克研究所",
    "locationEn": "USA·CA, Salk Institute"
  },
  {
    "id": "ethnography-118",
    "title": "《遮蔽的情感》(Veiled Sentiments)",
    "year": 1986,
    "author": "Lila Abu-Lughod",
    "publisher": "University of California Press",
    "summary": "埃及奥拉德阿里贝都因女性，如何通过诗歌表达被公开语言所压制的情感，包括对爱情、失落与怨恨的过渡性小诗。\n\n与贝都因女性群体的长期共居与参与观察。\n\n诗歌是女性在权威结构下服从与反抗的情感语法。",
    "location": "Western Desert",
    "countryOrRegion": "Egypt",
    "lat": 28.35,
    "lon": 29.0,
    "sourceField": "埃及 - 西部沙漠",
    "locationEn": "Egypt·Western Desert"
  },
  {
    "id": "ethnography-119",
    "title": "《希望的方法》(The Method of Hope)",
    "year": 2004,
    "author": "Hirokazu Miyazaki（宫崎広和）",
    "publisher": "Stanford University Press",
    "summary": "斐济苏瓦额人小岛民如何将对历史祈愿土地归还的希望，维持为第一性、跨越不同知识实践领域的存在性资源。  \n\n追踪请愿书、礼物交换、教堂仪式与商业活动的田野调查，结合康德、本雅明、罗蒂等哲学工作的对读分析。\n\n希望不是情感状态，而是知识形成的方法论工具。",
    "location": "Suvavou",
    "countryOrRegion": "Fiji",
    "lat": -18.1248,
    "lon": 178.4501,
    "sourceField": "斐济 - 苏瓦",
    "locationEn": "Fiji·Suvavou"
  },
  {
    "id": "ethnography-120",
    "title": "《上山采药》(Gathering Medicines)",
    "year": 2021,
    "author": "Judith Farquhar （冯珠娣）& Lili Lai（赖立里）",
    "publisher": "University of Chicago Press",
    "summary": "民族医学知识整理运动中，七个民族的传统医药知识如何在山区中被采集、分类与制度化。\n\n六年多点田野调查，跟随药物采集者并认真观察知识编码过程。\n\n民族医学并非静态的「传统」，而是在国家发展项目与地方知识的动态相遇中，不断被重新集结的过程。",
    "location": "Southwest Mountain Regions",
    "countryOrRegion": "China",
    "lat": 26.05,
    "lon": 103.15,
    "sourceField": "中国 - 西南山区",
    "locationEn": "China·Southwest Mountain Regions"
  },
  {
    "id": "ethnography-121",
    "title": "《反政治机器》(The Anti-Politics Machine)",
    "year": 1990,
    "author": "James Ferguson",
    "publisher": "Cambridge University Press",
    "summary": "莱索托的一个贫困乡村地区如何在西方发展项目的干预下，不断将政治问题技术化、将贫困去历史化与去政治化。\n\n对联合国及其刚支机构发布的发展报告进行话语分析，结合山区穿组的田野调查。\n\n「反政治机器」是发展话语的核心隐喻：将贫困归因于技术性缺陷，遮蔽其结构性根源，同时将国家权力运作通道延伸至履行边缘地区。",
    "location": "Lesotho",
    "countryOrRegion": "Lesotho",
    "lat": -29.61,
    "lon": 28.23,
    "sourceField": "莱索托",
    "locationEn": "Lesotho"
  },
  {
    "id": "ethnography-122",
    "title": "《阶序的流转》(The Traffic in Hierarchy)",
    "year": 2017,
    "author": "Ward Keeler",
    "publisher": "University of Hawaii Press",
    "summary": "曼德勒寺院与街头日常生活中，男性如何在成为僧侣、家主或跨性别者之间做出选择，揭示等级制度如何规定每种选择的特权与代价。\n\n曼德勒寺院及城市空间的长期参与田野调查，结合性别、宗教实践与杜蒙等级理论的综合分析。\n\n缅甸对等级的内化式认同是军政府得以长期统治的社会土壤；男性气质的多重形态共同揭示了依附与自主，作为缅甸社会组织核心原则的深层逻辑。",
    "location": "Yangon / Mandalay",
    "countryOrRegion": "Burma/Myanmar",
    "lat": 21.9588,
    "lon": 96.0891,
    "sourceField": "缅甸 - 仰光/曼德勒",
    "locationEn": "Burma / Myanmar·Yangon / Mandalay",
    "sites": [
      {
        "lat": 16.8409,
        "lon": 96.1735
      },
      {
        "lat": 21.9588,
        "lon": 96.0891
      }
    ]
  },
  {
    "id": "ethnography-123",
    "title": "《被扰动的边境资本主义》(Border Capitalism, Disrupted)",
    "year": 2018,
    "author": "Stephen Campbell",
    "publisher": "Cornell University Press",
    "summary": "泰缅边境湄索经济特区的缅甸移民劳工如何在资本弹性化、警察管控与非正规中介的交织下维系生存，并以流动性抗争推动劳动法规的在地转变。\n\n在湄索近两年的田野调查，追踪工人、警察、雇主、NGO与非正规护照中介的日常互动实践。\n\n工人的流动性抗争才是驱动边境资本主义重组的核心动力；全球南方的劳工脆弱性具有独特逻辑。",
    "location": "Mae Sot",
    "countryOrRegion": "Thailand (Myanmar-Thai Border)",
    "lat": 16.7167,
    "lon": 98.5667,
    "sourceField": "泰国（缅泰边境）- 湄索",
    "locationEn": "Thailand (Myanmar-Thai Border)·Mae Sot"
  },
  {
    "id": "ethnography-124",
    "title": "《拒斥权利》(Rights Refused)",
    "year": 2023,
    "author": "Elliott Prasse-Freeman",
    "publisher": "Stanford University Press",
    "summary": "缅甸2010年代政治转型期，民间活动人士如何在国家暴力与人权话语之间创造出犁地抗议、诅咒仪式与漫画等非常规抵抗策略。\n\n与农民、工人及全国各地社运人士历时十年的田野研究，结合2021年政变后的数字民族志与深度访谈。\n\n民众对人权话语的拒绝并非政治冷漠，而是一种主动的存在性策略；「拒斥」本身就是有效的政治实践。",
    "location": "",
    "countryOrRegion": "Burma/Myanmar",
    "lat": 21.9162,
    "lon": 95.956,
    "sourceField": "缅甸 Myanmar - 全国多地",
    "locationEn": "Burma/Myanmar·Nationwide"
  },
  {
    "id": "ethnography-125",
    "title": "《边际收益》(Marginal Gains)",
    "year": 2004,
    "author": "Jane I. Guyer",
    "publisher": "University of Chicago Press",
    "summary": "穿越数百年大西洋贸易史，分析尼日利亚货币交易实践中的\"边际收益\"逻辑：非洲经济行动者如何在多重货币与时间框架中，维持交换的开放性与创造力。  跨越历史档案与当代约鲁巴经济实践的多尺度民族志与比较分析。  非洲经济不是市场经济的残缺版本，而是一套以\"边际\"而非\"积累\"为核心的独特时间性逻辑；货币多元性是大西洋非洲应对不确定性的生存智慧。",
    "location": "Yoruba / Benin City (Atlantic Africa)",
    "countryOrRegion": "Nigeria",
    "lat": 6.335,
    "lon": 5.6037,
    "sourceField": "尼日利亚 - 约鲁巴/贝宁城（大西洋非洲）",
    "locationEn": "Nigeria·Yoruba / Benin City (Atlantic Africa)"
  },
  {
    "id": "ethnography-126",
    "title": "《创意的考量》(Creative Reckonings)",
    "year": 2006,
    "author": "Jessica Winegar",
    "publisher": "Stanford University Press",
    "summary": "开罗艺术家如何在国家文化机构、伊斯兰主义批评与西方艺术市场三重压力下，协商\"现代埃及艺术\"的意义、价值与合法性。\n\n开罗艺术院校、画廊、艺术家工作室与展览空间的长期参与田野调查，结合文化政策文本与媒体话语分析。\n\n\"当代艺术\"的全球化话语在埃及本土遭遇特定的伊斯兰与国家话语压力，艺术实践揭示了后殖民社会文化政治的内在张力。",
    "location": "Cairo",
    "countryOrRegion": "Egypt",
    "lat": 30.0444,
    "lon": 31.2357,
    "sourceField": "埃及 - 开罗",
    "locationEn": "Egypt·Cairo"
  },
  {
    "id": "ethnography-127",
    "title": "《无人哭泣的死亡》(Death Without Weeping)",
    "year": 1992,
    "author": "Nancy Scheper-Hughes",
    "publisher": "University of California Press",
    "summary": "巴西东北部贫困社区中，儿童高死亡率如何形塑母亲对婴儿夭折的情感反应，使悲恸成为一种\"延迟\"的文化实践。\n\n伯南布哥州农村及糖厂工人社区的长期田野调查，历时二十余年。\n\n在极端贫困的结构性暴力下，母亲对婴儿死亡的情感麻木并非冷漠，而是在匮乏中形成的生存适应；悲悼的缺席揭示了苦难的政治经济学根源。",
    "location": "Brazil · Northeast (Pernambuco)",
    "countryOrRegion": "Brazil · Northeast (Pernambuco)",
    "lat": -7.5053,
    "lon": -35.3181,
    "sourceField": "巴西·东北部（伯南布哥州）",
    "locationEn": "Brazil·Northeast (Pernambuco)"
  },
  {
    "id": "ethnography-128",
    "title": "《激情的抗争》(Passionate Uprisings)",
    "year": 2009,
    "author": "Pardis Mahdavi",
    "publisher": "Stanford University Press",
    "summary": "德黑兰年轻一代穆斯林如何在伊斯兰共和国的道德管制下，通过派对、约会与身体实践悄然推进一场\"性革命\"，重构个人自由与宗教认同的边界。\n\n德黑兰中上层青年聚会场所与日常社交空间的长期参与观察，结合青年男女的深度访谈与身体实践的细密民族志记录。\n\n揭示了伊斯兰革命后，伊朗国家话语与个人欲望之间的持续张力，伊朗年轻人的身体实践是提出异议的方式。",
    "location": "Tehran",
    "countryOrRegion": "Iran",
    "lat": 35.6892,
    "lon": 51.389,
    "sourceField": "伊朗 - 德黑兰",
    "locationEn": "Iran·Tehran"
  },
  {
    "id": "ethnography-129",
    "title": "《阿尔及利亚在法国》(Algeria in France)",
    "year": 2004,
    "author": "Paul Silverstein",
    "publisher": "Indiana University Press",
    "summary": "法国阿尔及利亚移民社区如何在后殖民记忆、法国种族政治与伊斯兰-柏柏尔文化认同的交叉地带，构建超越单一民族国家框架的跨国主体性。\n\n巴黎郊区阿尔及利亚移民社区田野调查，结合阿尔及利亚柏柏尔（卡拜利）运动档案与法国多元文化政策的比较分析。\n\n\"跨政治\"（transpolitics）超越民族国家边界，在离散社区中生产出新型的族群认同与后殖民批判政治。",
    "location": "Ile-de-France",
    "countryOrRegion": "Algeria / France",
    "lat": 48.8566,
    "lon": 2.3522,
    "sourceField": "阿尔及利亚·法国 - 巴黎大区",
    "locationEn": "Algeria / France·Ile-de-France"
  },
  {
    "id": "ethnography-130",
    "title": "《人权在摩洛哥的表演》(The Performance of Human Rights in Morocco)",
    "year": 2005,
    "author": "Susan Slyomovics",
    "publisher": "University of Pennsylvania Press",
    "summary": "摩洛哥\"公平与和解委员会\"对哈桑二世统治时期国家暴力受害者的赔偿实践，以及幸存者如何通过公开证言与纪念活动重新书写历史记忆。\n\n摩洛哥公开听证会、受害者社群、前政治犯与纪念空间的田野调查，结合人权文件、证言档案与过渡时期正义话语的批判分析。\n\n人权实践是一种\"表演\"；过渡时期正义的仪式与话语在揭示暴力的同时，也在国家框架内管控、限制了苦难表达与历史责任追究的范围。",
    "location": "Casablanca / Rabat / Kenitra",
    "countryOrRegion": "Morocco",
    "lat": 33.5731,
    "lon": -7.5898,
    "sourceField": "摩洛哥 - 卡萨布兰卡·拉巴特·克尼特拉",
    "locationEn": "Morocco·Casablanca / Rabat / Kenitra"
  },
  {
    "id": "ethnography-132",
    "title": "《抵抗的灵魂和资本主义规训》(Spirits of Resistance and Capitalist Discipline: Factory Women in Malaysia)",
    "year": 1987,
    "author": "Aihwa Ong（王爱华）",
    "publisher": "State University of New York Press",
    "summary": "马来西亚急速工业化浪潮中，农村穆斯林女性从稻田进入日资电子厂后经历的文化冲突与身份危机——包括震惊管理层的工厂灵魂附身事件。  雪兰莪州农业区的深度参与田野，结合历史分析与量化数据。  灵魂附身不是迷信，而是女工对资本主义纪律与性别规训的身体性抵抗；跨国资本的扩张深刻重塑了马来乡村社会的性别秩序与主体形态。",
    "location": "Selangor",
    "countryOrRegion": "Malaysia",
    "lat": 4.399,
    "lon": 101.53,
    "sourceField": "马来西亚 - 雪兰莪州",
    "locationEn": "Malaysia·Selangor"
  },
  {
    "id": "ethnography-134",
    "title": "《失落的人们》(Lost People: Magic and the Legacy of Slavery in Madagascar)",
    "year": 2007,
    "author": "David Graeber",
    "publisher": "Indiana University Press",
    "summary": "马达加斯加贝塔夫地区的巫术实践与奴隶制历史遗产，如何在当地社会关系与身份政治中延续至今。\n\n与村民长期共同生活的深度参与观察，结合历史档案与神话文本分析。\n\n被遗忘的历史不会消失，而是以鬼魂与魔法的形式潜伏于日常生活；价值、债务与记忆构成后奴隶制社会的深层结构。",
    "location": "Betafo",
    "countryOrRegion": "Madagascar",
    "lat": -19.87,
    "lon": 46.75,
    "sourceField": "马达加斯加 - 贝塔夫",
    "locationEn": "Madagascar·Betafo"
  },
  {
    "id": "ethnography-135",
    "title": "《在世界中安家》(At Home in the World)",
    "year": 1995,
    "author": "Michael Jackson",
    "publisher": "Duke University Press",
    "summary": "与澳大利亚塔纳米沙漠的瓦尔皮里人共同生活，追问游牧民族对「家」的理解如何挑战定居文明的归属观念。\n\n中澳大利亚瓦尔皮里社区的长期参与田野，结合个人生命叙事与现象学反思。\n\n「在家」不是固定地点，而是在流动中安身于世的存在方式；游牧者的栖居智慧为现代人的无根处境提供了另一种答案。",
    "location": "Tanami Desert",
    "countryOrRegion": "Australia",
    "lat": -25.27,
    "lon": 133.78,
    "sourceField": "澳大利亚 - 塔纳米沙漠",
    "locationEn": "Australia·Tanami Desert"
  },
  {
    "id": "ethnography-136",
    "title": "《跨国灰姑娘》(Global Cinderellas)",
    "year": 2006,
    "author": "Pei-Chia Lan（蓝佩嘉）",
    "publisher": "Duke University Press",
    "summary": "台湾中产与上层家庭如何雇用菲律宾与印尼移工担任家务与照护劳动，探讨跨国雇佣关系中双方对身份、情感与权力的协商。\n\n深度访谈与参与观察涵盖台湾雇主家庭与移工社群两端的田野调查。  \n\n移工以「跨国灰姑娘」之姿同时承受阶级、族裔与性别的多重支配；照护劳动的商品化与情感化共同揭示全球照护链中的结构性不平等。",
    "location": "Taiwan",
    "countryOrRegion": "Taiwan",
    "lat": 25.033,
    "lon": 121.565,
    "sourceField": "台湾",
    "locationEn": "Taiwan"
  },
  {
    "id": "ethnography-137",
    "title": "《猎人、牧人与牧场主》(Hunters, Pastoralists and Ranchers)",
    "year": 1980,
    "author": "Tim Ingold",
    "publisher": "Cambridge University Press",
    "summary": "比较北方极地社会中萨米驯鹿猎人、游牧牧人与现代牧场主三种不同的人与动物关系模式及其社会组织逻辑。\n\n芬兰拉普兰萨米人社区田野调查，结合北方游牧社会的跨文化比较分析。\n\n人与动物的关系不是固定的，而是随生计方式变化而变化；猎人、牧人与牧场主代表着三种截然不同的存在论与所有权观念。",
    "location": "Lapland",
    "countryOrRegion": "Finland",
    "lat": 66.504,
    "lon": 25.729,
    "sourceField": "芬兰 - 拉普兰",
    "locationEn": "Finland·Lapland"
  }
];
