window.ETHNOGRAPHY_BOOKS = [
  {
    "id": "ethnography-01",
    "title": "《维塔》(Vita)",
    "year": 2005,
    "author": "João Biehl",
    "publisher": "Princeton",
    "summary": "追踪巴西收容机构中被遗弃的精神病患者，以一名女性的生命为核心线索。\n\n结合长期田野、照片民族志与档案追溯。\n\n国家与家庭共谋将无用之人逐入遗弃区。",
    "location": "Porto Alegre",
    "countryOrRegion": "Brazil",
    "lat": -30.0346,
    "lon": -51.2177,
    "sourceField": "巴西 - 阿雷格里港",
    "locationEn": "Brazil · Porto Alegre"
  },
  {
    "id": "ethnography-02",
    "title": "《多重身体》(The Body Multiple)",
    "year": 2002,
    "author": "Annemarie Mol",
    "publisher": "Duke",
    "summary": "同一疾病在荷兰医院不同实践场景中呈现为多种截然不同的现实。\n\n跟踪检查、手术室、门诊等日常医学实践。\n\n疾病不是被发现的，而是在不同实践中被多元地制造出来的。",
    "location": "Utrecht",
    "countryOrRegion": "Netherlands",
    "lat": 52.0907,
    "lon": 5.1214,
    "sourceField": "荷兰 - 乌得勒支",
    "locationEn": "Netherlands · Utrecht"
  },
  {
    "id": "ethnography-03",
    "title": "《暴露下的生命》(Life Exposed)",
    "year": 2002,
    "author": "Adriana Petryna",
    "publisher": "Princeton",
    "summary": "切尔诺贝利核灾后，乌克兰人以受损的身体换取国家补偿与公民权利。\n\n基辅及灾区田野调查结合政策文件研究。\n\n受苦的身体成为政治谈判资本，催生后苏联时代的新型公民身份。",
    "location": "Kyiv / Chernobyl Region",
    "countryOrRegion": "Ukraine",
    "lat": 50.2,
    "lon": 30.3,
    "sourceField": "乌克兰 - 基辅/切尔诺贝利区域",
    "locationEn": "Ukraine · Kyiv / Chernobyl region"
  },
  {
    "id": "ethnography-04",
    "title": "《即兴医疗》(Improvising Medicine)",
    "year": 2012,
    "author": "Julie Livingston",
    "publisher": "Duke",
    "summary": "博茨瓦纳唯一癌症病房中的照护、生死处置与医护伦理。\n\n长期病房民族志与患者及医护人员访谈。\n\n资源匮乏催生医疗即兴，既揭示全球卫生不平等，也彰显照护者的伦理创造力。",
    "location": "Gaborone",
    "countryOrRegion": "Botswana",
    "lat": -24.6282,
    "lon": 25.9231,
    "sourceField": "博茨瓦纳 - 哈博罗内",
    "locationEn": "Botswana · Gaborone"
  },
  {
    "id": "ethnography-05",
    "title": "《治疗共和国》(The Republic of Therapy)",
    "year": 2010,
    "author": "Vinh-Kim Nguyen",
    "publisher": "Duke",
    "summary": "西非艾滋病危机中，抗病毒药物的稀缺分配如何重塑患者的身份与主体性。\n\n布基纳法索与科特迪瓦多地田野调查。\n\n获得治疗的机会制造了新型生命政治身份，药物分配即政治分配。",
    "location": "Burkina Faso / Cote d'Ivoire",
    "countryOrRegion": "West Africa",
    "lat": 10.5,
    "lon": -4.5,
    "sourceField": "西非 - 布基纳法索/科特迪瓦",
    "locationEn": "West Africa · Burkina Faso / Côte d'Ivoire"
  },
  {
    "id": "ethnography-06",
    "title": "《乡间诊所》(The Pastoral Clinic)",
    "year": 2010,
    "author": "Angela Garcia",
    "publisher": "UC Press",
    "summary": "新墨西哥州西裔社区代际传承的海洛因成瘾与难以言说的悲恸。\n\n埃斯帕诺拉河谷长期田野调查与家庭访谈。\n\n成瘾根植于土地丧失与历史创伤，是悲恸的身体表达，而非个人道德缺陷。",
    "location": "Espanola Valley, New Mexico",
    "countryOrRegion": "United States",
    "lat": 36.0,
    "lon": -106.1,
    "sourceField": "美国 - 新墨西哥州 埃斯帕诺拉河谷",
    "locationEn": "United States · Española Valley, New Mexico"
  },
  {
    "id": "ethnography-07",
    "title": "《债中生活》(Life in Debt)",
    "year": 2012,
    "author": "Clara Han",
    "publisher": "UC Press",
    "summary": "圣地亚哥贫困社区在新自由主义改革下的债务、照护与亲密关系。\n\n长期社区民族志，深入家庭日常。\n\n债务渗透底层的伦理互助，重塑亲属间的依存关系，使照护本身成为负重的实践。",
    "location": "Santiago",
    "countryOrRegion": "Chile",
    "lat": -33.4489,
    "lon": -70.6693,
    "sourceField": "智利 - 圣地亚哥",
    "locationEn": "Chile · Santiago"
  },
  {
    "id": "ethnography-08",
    "title": "《新鲜的水果，破碎的身体》(Fresh Fruit, Broken Bodies)",
    "year": 2013,
    "author": "Seth Holmes",
    "publisher": "UC Press",
    "summary": "墨西哥移民农工在美国的迁徙、劳动与身体受苦。\n\n亲身随工人下地务农的参与式观察。\n\n结构性暴力与种族化将不平等铭刻于工人身体，并将他们的痛苦自然化、正常化。",
    "location": "Oaxaca",
    "countryOrRegion": "Mexico / United States",
    "lat": 17.0732,
    "lon": -96.7266,
    "sourceField": "美国(华盛顿州)-墨西哥(瓦哈卡)",
    "locationEn": "United States (Washington State) · Mexico (Oaxaca)",
    "sites": [
      {
        "lat": 48.4193,
        "lon": -122.3349
      },
      {
        "lat": 17.0732,
        "lon": -96.7266
      }
    ]
  },
  {
    "id": "ethnography-09",
    "title": "《权力的病理学》(Pathologies of Power)",
    "year": 2003,
    "author": "Paul Farmer",
    "publisher": "UC Press",
    "summary": "全球贫富不平等如何系统性地剥夺海地、秘鲁等地人群的健康权利。\n\n多地临床田野调查与跨学科批判分析。\n\n结构性暴力是疾病的根源；健康即人权，医学人类学必须直面社会不正义。",
    "location": "Multi-sited: Haiti/Peru/Russia/Cuba",
    "countryOrRegion": "Global Multi-site",
    "lat": 19.0,
    "lon": -72.3,
    "sourceField": "海地、秘鲁、俄罗斯、古巴",
    "locationEn": "Haiti · Peru · Russia · Cuba",
    "sites": [
      {
        "lat": 18.5944,
        "lon": -72.3074
      },
      {
        "lat": -12.0464,
        "lon": -77.0428
      },
      {
        "lat": 55.7558,
        "lon": 37.6173
      },
      {
        "lat": 23.1136,
        "lon": -82.3666
      }
    ]
  },
  {
    "id": "ethnography-10",
    "title": "《两度死亡》(Twice Dead)",
    "year": 2002,
    "author": "Margaret Lock",
    "publisher": "UC Press",
    "summary": "脑死亡定义与器官移植在日本与北美引发的截然不同的认知与争议。\n\n跨文化比较民族志与医学史研究。\n\n死亡是社会建构而非生物事实；文化的局部知识塑造了不同的身体政治。",
    "location": "Tokyo / Montreal",
    "countryOrRegion": "Japan / North America",
    "lat": 35.6762,
    "lon": 139.6503,
    "sourceField": "日本 - 东京 / 北美 - 蒙特利尔等",
    "locationEn": "Japan · Tokyo / North America · Montreal (and environs)",
    "sites": [
      {
        "lat": 35.6762,
        "lon": 139.6503
      },
      {
        "lat": 45.5019,
        "lon": -73.5674
      }
    ]
  },
  {
    "id": "ethnography-11",
    "title": "《末日松茸》(The Mushroom at the End of the World)",
    "year": 2015,
    "author": "Anna Tsing",
    "publisher": "Princeton",
    "summary": "松茸商品链串联美国、日本、中国、芬兰的劳动、生态与多物种关系。\n\n多点田野调查，追踪松茸从森林到市场的全程。\n\n在资本主义废墟中，非正规合作与多物种共存仍可孕育生机，挑战线性进步叙事。",
    "location": "Oregon-Japan-China-Finland Network",
    "countryOrRegion": "Transnational",
    "lat": 44.0582,
    "lon": -121.3153,
    "sourceField": "美国(俄勒冈)-日本-中国-芬兰",
    "locationEn": "United States (Oregon) · Japan · China · Finland"
  },
  {
    "id": "ethnography-12",
    "title": "《森林如何思考》(How Forests Think)",
    "year": 2013,
    "author": "Eduardo Kohn",
    "publisher": "UC Press",
    "summary": "厄瓜多尔卢纳人与亚马逊森林之间的符号互动与跨物种共处方式。\n\n阿维拉社区长期田野调查，结合皮尔斯符号学理论。\n\n符号与思考超越人类边界；森林本身是自我组织的符号过程，呼唤超越人类的人类学。",
    "location": "Avila, Ecuadorian Amazon",
    "countryOrRegion": "Ecuador",
    "lat": -0.67,
    "lon": -77.72,
    "sourceField": "厄瓜多尔 - 阿维拉",
    "locationEn": "Ecuador · Ávila"
  },
  {
    "id": "ethnography-13",
    "title": "《在棕榈的阴影下》(In the Shadow of the Palms)",
    "year": 2022,
    "author": "Sophie Chao",
    "publisher": "Duke",
    "summary": "油棕种植园扩张对印尼西巴布亚马林德人多物种世界的系统性摧毁。\n\n社区民族志与多物种田野考察。\n\n工业农业造成存在性灾难：不仅是生态危机，更是本体论意义上的世界终结与哀悼。",
    "location": "West Papua, Morau River",
    "countryOrRegion": "Indonesia",
    "lat": -1.3,
    "lon": 133.5,
    "sourceField": "印尼 - 西巴布亚 莫劳河区域",
    "locationEn": "Indonesia · Morau River, West Papua"
  },
  {
    "id": "ethnography-14",
    "title": "《飞行之路》(Flight Ways)",
    "year": 2014,
    "author": "Thom van Dooren",
    "publisher": "Columbia",
    "summary": "濒危鸟类的灭绝过程、保育劳动及其引发的伦理困境。\n\n跟随保育工作者与鸟类的多地民族志。\n\n灭绝是世代延续的生活方式之终结；哀悼与伦理责任是回应物种消失的恰当姿态。",
    "location": "Hawaii & Australia Flyways",
    "countryOrRegion": "Pacific Region",
    "lat": 21.3069,
    "lon": -157.8583,
    "sourceField": "澳大利亚、美国(夏威夷)",
    "locationEn": "Australia · United States (Hawaii)",
    "sites": [
      {
        "lat": 21.3069,
        "lon": -157.8583
      },
      {
        "lat": -33.8688,
        "lon": 151.2093
      }
    ]
  },
  {
    "id": "ethnography-15",
    "title": "《动物亲缘》(Animal Intimacies)",
    "year": 2018,
    "author": "R. Govindrajan",
    "publisher": "Chicago",
    "summary": "印度库曼山区人与动物间的情感、献祭与日常共处关系。\n\n社区参与观察与深度访谈。\n\n人与动物通过照料与暴力建立亲缘；跨物种关系挑战人类中心主义的亲密边界。",
    "location": "Kumaon Himalaya",
    "countryOrRegion": "India",
    "lat": 29.6,
    "lon": 79.6,
    "sourceField": "印度 - 库曼山区",
    "locationEn": "India · Kumaon Himalaya"
  },
  {
    "id": "ethnography-16",
    "title": "《猪肉城》(Porkopolis)",
    "year": 2020,
    "author": "Alex Blanchette",
    "publisher": "Duke",
    "summary": "美国中西部工业猪肉生产中人与猪如何共同被纳入资本主义生产流水线。\n\n在屠宰场长期从业的深度参与民族志。\n\n工业单一文化将猪的生物节律强加于人类劳动，人与动物一同被化约为生产单元。",
    "location": "U.S. Midwest (Nebraska)",
    "countryOrRegion": "United States",
    "lat": 41.5,
    "lon": -99.8,
    "sourceField": "美国 - 中西部（内布拉斯加州等）",
    "locationEn": "United States · Midwest (Nebraska, etc.)"
  },
  {
    "id": "ethnography-17",
    "title": "《异星海洋》(Alien Ocean)",
    "year": 2009,
    "author": "Stefan Helmreich",
    "publisher": "UC Press",
    "summary": "海洋微生物学家对深海生命边界的科学探索与认知建构。\n\n实验室与科考船田野调查。\n\n深海微生物挑战关于生命与自然的既有范畴；科学实践与资本共同建构海洋的本体。",
    "location": "Hawaii/California & High Seas",
    "countryOrRegion": "Pacific Ocean",
    "lat": 23.0,
    "lon": -155.0,
    "sourceField": "美国 - 夏威夷/加州实验室及公海",
    "locationEn": "United States · Hawaii / California labs · high seas"
  },
  {
    "id": "ethnography-18",
    "title": "《去殖民化灭绝》(Decolonizing Extinction)",
    "year": 2018,
    "author": "J. S. Parreñas",
    "publisher": "Duke",
    "summary": "马来西亚砂拉越猩猩康复机构中的照护实践、与殖民遗产的纠缠。\n\n机构民族志与工作者深度访谈。\n\n保育工作内嵌于殖民关系；去殖民化需正视照护行为的矛盾性，而非浪漫化救援。",
    "location": "Sarawak",
    "countryOrRegion": "Malaysia",
    "lat": 2.5,
    "lon": 113.5,
    "sourceField": "马来西亚 - 砂拉越",
    "locationEn": "Malaysia · Sarawak"
  },
  {
    "id": "ethnography-19",
    "title": "《与牧群共生》(Living with Herds)",
    "year": 2011,
    "author": "Natasha Fijn",
    "publisher": "Cambridge",
    "summary": "蒙古游牧民与畜群之间的共同演化、日常互动与相互塑造。\n\n与牧民共同生活的长期参与田野调查。\n\n家畜是具有能动性的伙伴；人与动物通过长期共处形成跨物种的关系性社会。",
    "location": "Arkhangai Mountains",
    "countryOrRegion": "Mongolia",
    "lat": 47.7,
    "lon": 101.0,
    "sourceField": "蒙古 - 杭爱山脉",
    "locationEn": "Mongolia · Khangai Mountains (Arkhangai)"
  },
  {
    "id": "ethnography-20",
    "title": "《道德实验室》(Moral Laboratories)",
    "year": 2014,
    "author": "Cheryl Mattingly",
    "publisher": "UC Press",
    "summary": "洛杉矶非裔美国家庭在照护慢性病儿童过程中的日常道德实践。\n\n长期家庭民族志与叙事分析。\n\n伦理是在实验与叙事中生成的实践，而非规则遵循；普通家庭是真实的道德哲学实验室。",
    "location": "Los Angeles",
    "countryOrRegion": "United States",
    "lat": 34.0522,
    "lon": -118.2437,
    "sourceField": "美国 - 洛杉矶",
    "locationEn": "United States · Los Angeles"
  },
  {
    "id": "ethnography-21",
    "title": "《成为罪人》(Becoming Sinners)",
    "year": 2004,
    "author": "Joel Robbins",
    "publisher": "UC Press",
    "summary": "巴布亚新几内亚乌拉普明人皈依基督教后经历的道德与文化深层转型。\n\n部落社区长期田野调查。\n\n文化变迁可以是彻底的断裂；乌拉普明人真诚内化了基督教罪感伦理，而非表面融合。",
    "location": "Urapmin",
    "countryOrRegion": "Papua New Guinea",
    "lat": -5.2,
    "lon": 141.4,
    "sourceField": "巴布亚新几内亚 - 乌拉普明部落",
    "locationEn": "Papua New Guinea · Urapmin"
  },
  {
    "id": "ethnography-22",
    "title": "《正义的瘾君子》(Righteous Dopefiend)",
    "year": 2009,
    "author": "P. Bourgois",
    "publisher": "UC Press",
    "summary": "旧金山无家可归海洛因成瘾者的日常生存、道德世界与相互照料。\n\n长期田野调查结合黑白照片民族志。\n\n成瘾者在结构性暴力中仍维系道德经济；社会排斥才是成瘾的根源，而非个体失德。",
    "location": "San Francisco",
    "countryOrRegion": "United States",
    "lat": 37.7749,
    "lon": -122.4194,
    "sourceField": "美国 - 旧金山",
    "locationEn": "United States · San Francisco"
  },
  {
    "id": "ethnography-23",
    "title": "《美德的主体》(The Subject of Virtue)",
    "year": 2013,
    "author": "James Laidlaw",
    "publisher": "Cambridge",
    "summary": "印度耆那教苦行者的伦理修行实践与自由概念的人类学反思。\n\n斋浦尔苦行者社群的田野调查。\n\n美德需要自由；伦理不是习惯养成，而是自觉的自我培育，挑战功利主义与共同体主义。",
    "location": "Jaipur, Rajasthan",
    "countryOrRegion": "India",
    "lat": 26.9124,
    "lon": 75.7873,
    "sourceField": "印度 - 拉贾斯坦邦/斋浦尔",
    "locationEn": "India · Rajasthan / Jaipur"
  },
  {
    "id": "ethnography-24",
    "title": "《虔诚的政治》(Politics of Piety)",
    "year": 2005,
    "author": "Saba Mahmood",
    "publisher": "Princeton",
    "summary": "开罗清真寺女性运动中的虔诚实践与伊斯兰伦理主体的形成。\n\n开罗女性清真寺运动的田野调查。\n\n服从与虔诚也是能动性的表达；质疑自由主义女性主义对能动性概念的狭隘预设。",
    "location": "Cairo",
    "countryOrRegion": "Egypt",
    "lat": 30.0444,
    "lon": 31.2357,
    "sourceField": "埃及 - 开罗",
    "locationEn": "Egypt · Cairo"
  },
  {
    "id": "ethnography-25",
    "title": "《生命之侧》(Life Beside Itself)",
    "year": 2014,
    "author": "Lisa Stevenson",
    "publisher": "UC Press",
    "summary": "加拿大因纽特人的自杀危机与国家匿名照护机制的冷漠结构。\n\n努纳武特地区田野调查结合精神分析理论。\n\n国家照护管理生命却忽视灵魂；因纽特人的图像思维揭示另一种生命政治的可能。",
    "location": "Nunavut",
    "countryOrRegion": "Canada",
    "lat": 66.0,
    "lon": -86.0,
    "sourceField": "加拿大 - 努纳武特地区",
    "locationEn": "Canada · Nunavut"
  },
  {
    "id": "ethnography-26",
    "title": "《一心一意》(A Heart for the Work)",
    "year": 2010,
    "author": "Claire Wendland",
    "publisher": "Chicago",
    "summary": "马拉维医学生在资源极度匮乏条件下接受训练并形成医者伦理的过程。\n\n医学院与医院的田野调查。\n\n非洲医学培训塑造独特使命感；医生在匮乏中学会为工作奉献之心。",
    "location": "Blantyre",
    "countryOrRegion": "Malawi",
    "lat": -15.7861,
    "lon": 35.0058,
    "sourceField": "马拉维 - 布兰太尔",
    "locationEn": "Malawi · Blantyre"
  },
  {
    "id": "ethnography-27",
    "title": "《生存的意志》(The Will to Live)",
    "year": 2005,
    "author": "João Biehl",
    "publisher": "Princeton",
    "summary": "巴西艾滋病患者如何通过法律诉讼争取免费药物，以及由此形成的生命政治格局。\n\n田野调查结合法律档案与患者访谈。\n\n生存的意志经由法律与制度化得以实现；巴西艾滋病治疗将药物可及性转化为公民权利。",
    "location": "Salvador & Southern Cities",
    "countryOrRegion": "Brazil",
    "lat": -12.9777,
    "lon": -38.5016,
    "sourceField": "巴西 - 萨尔瓦多/南部城市",
    "locationEn": "Brazil · Salvador / southern Brazilian cities"
  },
  {
    "id": "ethnography-28",
    "title": "《生活与言词》(Life and Words)",
    "year": 2006,
    "author": "Veena Das",
    "publisher": "UC Press",
    "summary": "印度分治暴力与博帕尔灾难在德里贫民窟中留下的创伤记忆与日常承担。\n\n德里社区长期田野调查与深度对话式访谈。\n\n日常生活是消化暴力的场所；降入日常是幸存者在创伤裂缝中重建可居世界的生命实践。",
    "location": "Delhi",
    "countryOrRegion": "India",
    "lat": 28.6139,
    "lon": 77.209,
    "sourceField": "印度 - 德里",
    "locationEn": "India · Delhi"
  },
  {
    "id": "ethnography-30",
    "title": "《坠落的天空》(The Falling Sky)",
    "year": 2013,
    "author": "Davi Kopenawa",
    "publisher": "Harvard",
    "summary": "亚诺马米萨满对本民族宇宙观、森林知识与生存危机的第一人称叙述。\n\n与人类学家合作完成的自述式民族志，历时数十年。\n\n亚诺马米宇宙观构成对西方商品拜物教的深刻批判；萨满劳作维系着天空与世界。",
    "location": "Amazon Forest (Brazil/Venezuela)",
    "countryOrRegion": "Brazil / Venezuela",
    "lat": 1.0,
    "lon": -63.0,
    "sourceField": "巴西/委内瑞拉 - 亚马逊森林",
    "locationEn": "Brazil / Venezuela · Amazon rainforest"
  },
  {
    "id": "ethnography-31",
    "title": "《大地之灵》(Earth Beings)",
    "year": 2015,
    "author": "M. de la Cadena",
    "publisher": "Duke",
    "summary": "秘鲁安第斯土著政治实践中非人类的大地存在（tirakuna）所扮演的能动角色。\n\n安第斯山区田野调查结合本体论分析。\n\n土著政治纳入了非人类存在；这颠覆了现代民主政治的人类中心主义前提。",
    "location": "Ausangate, Andes",
    "countryOrRegion": "Peru",
    "lat": -13.787,
    "lon": -71.229,
    "sourceField": "秘鲁 - 安第斯山区 奥桑加特山",
    "locationEn": "Peru · Ausangate, Peruvian Andes"
  },
  {
    "id": "ethnography-32",
    "title": "《超越自然与文化》(Beyond Nature and Culture)",
    "year": 2013,
    "author": "Philippe Descola",
    "publisher": "Chicago",
    "summary": "对四种人类与非人类关系模式（泛灵论、图腾主义、类比论、自然主义）的跨文化比较。\n\n泛亚马逊田野调查结合结构分析。\n\n自然与文化的二元对立是西方独有的本体论；泛灵论等其他模式提供了同等有效的世界观。",
    "location": "Ecuadorian Pan-Amazon",
    "countryOrRegion": "Ecuador / Pan-Amazon",
    "lat": -1.5,
    "lon": -76.5,
    "sourceField": "厄瓜多尔、泛亚马逊区域",
    "locationEn": "Ecuador · Pan-Amazon region"
  },
  {
    "id": "ethnography-33",
    "title": "《食人族形而上学》(Cannibal Metaphysics)",
    "year": 2014,
    "author": "E. V. de Castro",
    "publisher": "Univocal",
    "summary": "亚马逊原住民视角主义：所有存在共享文化视角，但拥有各自不同的身体与自然。\n\n比较神话学与跨部落民族志的理论重构。\n\n多自然主义颠覆西方多文化主义；原住民思想应被视为与西方哲学平等的智识传统。",
    "location": "Amazon Basin",
    "countryOrRegion": "Brazil",
    "lat": -3.0,
    "lon": -62.0,
    "sourceField": "巴西 - 亚马逊河流域",
    "locationEn": "Brazil · Amazon Basin"
  },
  {
    "id": "ethnography-34",
    "title": "《运动中的真理》(Truth in Motion)",
    "year": 2012,
    "author": "Martin Holbraad",
    "publisher": "Chicago",
    "summary": "古巴伊法占卜仪式中，神圣粉末与真理之间的本体论关系。\n\n哈瓦那伊法祭司社群的田野调查。\n\n粉末本身即真理而非象征真理；本体论转向要求我们从田野重建人类学分析概念。",
    "location": "Havana",
    "countryOrRegion": "Cuba",
    "lat": 23.1136,
    "lon": -82.3666,
    "sourceField": "古巴 - 哈瓦那",
    "locationEn": "Cuba · Havana"
  },
  {
    "id": "ethnography-35",
    "title": "《为多元宇宙设计》(Designs for the Pluriverse)",
    "year": 2018,
    "author": "Arturo Escobar",
    "publisher": "Duke",
    "summary": "哥伦比亚土著与非裔社区对替代性自治生活方式与去殖民化设计的探索。\n\n参与式行动研究与社区田野调查。\n\n多元宇宙设计对抗全球化的单一世界逻辑；设计可以成为去殖民化的政治认识论实践。",
    "location": "Cauca Valley",
    "countryOrRegion": "Colombia",
    "lat": 2.5,
    "lon": -76.5,
    "sourceField": "哥伦比亚 - 考卡河谷",
    "locationEn": "Colombia · Cauca Valley"
  },
  {
    "id": "ethnography-36",
    "title": "《魂灵猎人》(Soul Hunters)",
    "year": 2007,
    "author": "Rane Willerslev",
    "publisher": "UC Press",
    "summary": "西伯利亚尤卡吉尔猎人的模仿狩猎哲学：通过变成猎物来接近并诱捕它们。\n\n作者随猎人共同狩猎的深度参与民族志。\n\n猎人须在模仿与保持人性间维持危险平衡；泛灵论不是信仰，而是务实的存在论策略。",
    "location": "Siberia, Yukaghir Region",
    "countryOrRegion": "Russia",
    "lat": 68.7,
    "lon": 153.0,
    "sourceField": "俄罗斯 - 西伯利亚 尤卡吉尔地区",
    "locationEn": "Russia · Yukaghir Region, Siberia"
  },
  {
    "id": "ethnography-37",
    "title": "《现代性的神灵》(Spirits of Modernity)",
    "year": 2005,
    "author": "Harry G. West",
    "publisher": "Chicago",
    "summary": "莫桑比克穆埃达高原马孔德人的巫术话语与现代权力批判。\n\n高原社区田野调查结合政治历史分析。\n\n巫术是批判权力的本土语言；国家暴力与历史变迁通过巫术想象被体验、争议与诠释。",
    "location": "Mueda Plateau",
    "countryOrRegion": "Mozambique",
    "lat": -11.67,
    "lon": 39.56,
    "sourceField": "莫桑比克 - 穆埃达高原",
    "locationEn": "Mozambique · Mueda Plateau"
  }
];
